### ISSUE TITLE
IPv6 detect issue?

### ISSUE THREAD

**Issue by SunFulong** [wp-statistics/wp-statistics#105]
Hi, I've set up wp statistics 12.3.1 on latest wp, but it shows "PHP IPv6 Enabled: No", and my client IP turns 127.0.0.1.
I'm sure my IPv6 support is enable in my PHP 7.0.25, you can check here https://blog.sunfulong.me/phpinfo.php to find my configurations.
What's wrong with it? Or what can I do to fix it?

**Comment by mostafasoufi** [comment]
Hi @SunFulong,

We use `AF_INET6` for check that. Please make sure this constant have a value in your PHP.

**Comment by SunFulong** [comment]
OK, I was compiled with ipv6 but without sockets switch, after I enabled it, now it works!
But, is this a detect issue? I'm sure without sockets switch, IPv6 can work functional.

**Comment by mostafasoufi** [comment]
I think it's the only way to check IPv6 status in the PHP.

**Comment by SunFulong** [comment]
OK, I'm not an PHP developer, so I don't know how dose it work, thank you for your anwser!

**Comment by mostafasoufi** [comment]
Your welcome.
