### ISSUE TITLE
Exclude "Related Post by Jetpack" Ajax Requests

### ISSUE THREAD

**Issue by kevinptt0323** [wp-statistics/wp-statistics#108]
[Related Posts](https://jetpack.com/support/related-posts/) is a feature of Jetpack, which will send an ajax to get related posts of current post.

Their ajax request to the API will be count as hits incorrectly.

Please add an option to exclude it.

API Url: http://example.com/2018/01/my-post/?relatedposts=1

**Comment by mostafasoufi** [comment]
Thank you @kevinptt0323,

We'll check that.

cc @Dedi-Data

**Comment by kevinptt0323** [comment]
No it doesn't really work.
"Excluded AJAX calls" only excludes AJAX from `admin-ajax.php`.
Ref: https://github.com/wp-statistics/wp-statistics/blob/master/includes/classes/class-wp-statistics-hits.php#L99

**Comment by kevinptt0323** [comment]
No it doesn't really work.
"Excluded AJAX calls" only excludes AJAX from `admin-ajax.php`.
Ref: https://github.com/wp-statistics/wp-statistics/blob/master/includes/classes/class-wp-statistics-hits.php#L98

**Comment by kevinptt0323** [comment]
BTW, it seems like the option `exclude_ajax` does not be checked before L98, so AJAX requests from `admin-ajax.php` will always be excluded.

**Comment by kevinptt0323** [comment]
@mostafasoufi

**Comment by mostafasoufi** [comment]
@kevinptt0323,
This issue will be open to check and more review.
