### ISSUE TITLE
Duplicate entry in log_error file

### ISSUE THREAD

**Issue by amrreko** [wp-statistics/wp-statistics#114]
`Duplicate entry '2018-02-24-/mysiteurl/?gclid=E' for key 'date_2'
INSERT INTO `wp_statistics_pages` (`uri`, `date`, `count`, `id`) VALUES ('/mysiteurl/?gclid=EAIaIQpbChMIj8v_lqW-2QIVjpztCh0-0QhVEAEYASAAEgJdz_D_BwE', '2018-02-24', 1, '14') Comming from require('wp-blog-header.php'), wp, WP->main, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, WP_Statistics_Frontend::init, WP_Statistics_Hits->Pages`

i used google adwords sign for url attribute.

**Comment by mostafasoufi** [comment]
Did you copy the plugin database to another one?

**Comment by amrreko** [comment]
No, i didn't but i use long url parameters that comming from Google Adwords like
`/?gclid=EAIaIQpbChMIj8v_lqW-2QIVjpztCh0-0QhVEAEYASAAEgJdz_D_BwE`
after any url from Google Adwords changes per visitor

**Comment by mostafasoufi** [comment]
Run the below query in your MySQL to skip this issue:
ALTER TABLE wp_statistics_pages DROP INDEX date_2;

**Comment by amrreko** [comment]
thank you, i will try, and will give you feedback

**Comment by wixaw** [comment]
Hello  @mostafasoufi @mehrshaddarzi 
We have a similar error regularly on WP5.2. Will this be fixed on version 13?

`Erreur de la base de données WordPress Duplicate entry '2019-09-06' for key 'unique_date' pour la requête INSERT INTO `wpxxx_statistics_visit` (`last_visit`, `last_counter`, `visit`) VALUES ('', '2019-09-06', 0) faite par do_action_ref_array('wp_statistics_add_visit_hook'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Statistics_Schedule->add_visit_event, W3TC\DbCache_Wpdb->insert, W3TC\DbCache_WpdbInjection_QueryCaching->insert, W3TC\_CallUnderlying->insert, W3TC\DbCache_Wpdb->insert, W3TC\DbCache_WpdbInjection->insert, W3TC\DbCache_Wpdb->default_insert, W3TC\DbCache_Wpdb->query, W3TC\DbCache_WpdbInjection->query, W3TC\DbCache_Wpdb->default_query`

Thanks
William
