### ISSUE TITLE
unrealistic data issues

### ISSUE THREAD

**Issue by malborinorosso** [wp-statistics/wp-statistics#115]
extreme differences with google analytics. I might understand a few missed users, but g-analytics gives me 37 for yesterday, while wp-stats gives 158 users. Page views for g-analytics 52 ,and for wp-stats 429. please help - https://pornhy.com

**Comment by mostafasoufi** [comment]
There are several reason for this issue in the below link:
https://wp-statistics.com/2017/05/26/im-using-another-statistics-pluginservice-and-get-different-numbers-for-them-why/
