### ISSUE TITLE
Google Search words PROBLEM

### ISSUE THREAD

**Issue by poyagh** [wp-statistics/wp-statistics#116]
Hi. My problem:
![image](https://user-images.githubusercontent.com/29813203/37470176-2fb726aa-287c-11e8-98b9-e9ad4e17838a.png)
No any related words for my site

**Comment by mostafasoufi** [comment]
Dupplicate https://github.com/wp-statistics/wp-statistics/issues/102

We'll try to find a solution to fix this issue.
