### ISSUE TITLE
Add bar chart as an alternative to line chart for all statistics

### ISSUE THREAD

**Issue by cpbotha** [wp-statistics/wp-statistics#117]
This is a really wonderful plugin, except for the fact that it uses an interpolated line chart to show discretized statistics.

From a visualization standpoint, this makes no sense. We are looking at discretized (daily, weekly, monthly) data, drawing smooth curves from point to point adds no value whatsoever.

Please consider adding a bar chart option to view all time-based stats. 

For hits use a grouped bar chart (visits, hits) and for search engine referrals use a stacked bar chart.

To re-iterate: Line charts are not the right chart type for this type of data, bar charts are.

(If you made this a paid add-on, I would buy it in a flash, and my eyes would be grateful.)

**Comment by mostafasoufi** [comment]
Hi @cpbotha,

Thank you for suggesting, It seems useful and to help and improve this idea, can you provide an example bar chart? (Screenshot is enough)

**Comment by cpbotha** [comment]
Below are two examples of a modified grouped bar chart showing visits and visitors, and below that a single page with its monthly views.

![image](https://user-images.githubusercontent.com/937871/38174263-f539e236-35ca-11e8-8ae0-1d55e31e0157.png)

![image](https://user-images.githubusercontent.com/937871/38174277-27de182e-35cb-11e8-8410-50b3badeec6c.png)

**Comment by mostafasoufi** [comment]
Thank you @cpbotha

**Comment by onny** [comment]
Summarized hits/visits per month would be awesome!

**Comment by Matherone** [comment]
Exactly. Good point. Much needed.

As @cpbotha suggests, discrete aggregates, for example the number of visitors during a given time slot, should be displayed by **discrete ink**. For example as vertical bars that are detached from each other by space between them. Never as a continuous line. 

WP Statistics appears to currently use pseudointerpolated continuous graphs. But from a statistical visualisation point of view, continous lines are here at best **nonsense**. 

In the screenshots Cpbotha provides, similar to Jetpack's, the aggregate for each day (month, year, etc) correctly has its own, discrete bar. This is a good conceptual start.

Please change the way WP Statistis visualises aggregate numbers over time. Stop using continuous lines. 
**Replace it with discrete vertical bars**.

If you want to better understand how to visualise statistics, please read the excellent textbook _[The Visual Display of Quantitative Information](https://www.amazon.com/Visual-Display-Quantitative-Information/dp/1930824130)_ by Edward R Tufte.

**Comment by mehrshaddarzi** [comment]
Thanks a lot for participating in this issue.
this future is done and released in a new version soon.

Commit :
https://github.com/wp-statistics/wp-statistics/commit/a8260eae846d320f47de337771664614d76c1542

Screenshot:

![1](https://user-images.githubusercontent.com/949491/58534691-2ba01380-8201-11e9-9c90-b790893238f1.JPG)

![2](https://user-images.githubusercontent.com/949491/58534692-2ba01380-8201-11e9-91be-f0c6a3b69f25.JPG)

**Comment by cpbotha** [comment]
How do those line charts address this issue, which is even titled "bar chart" ?

Again: According to visualization principles, you really should not use an interpolated line chart to show discrete values. In other words, use a bar chart, and don't use an interpolated line chart.

**Comment by Matherone** [comment]
Agreed. The screenshots supplied by @mehrshaddarzi do not address this issue.

A website's number of visits and visitors per day are discrete numbers. Since they are discrete numbers, they should be **presented as discrete numbers**. Please do not display discrete numbers as some kind of continuous pseudofunction. The current implementation and the screenshot above are **statistical nonsense** and are misleading to the user.

Please just **use simple bar charts** instead.

**Comment by mostafasoufi** [comment]
The provided screenshots are one of WP-Statistics widgets which customization in the Settings page for change the type of chart.

And in our plan, we've some new numeric widgets.

I wanna change to open to get feedbacks.
