### ISSUE TITLE
Documentation of measures for privacy protection

### ISSUE THREAD

**Issue by cgogolin** [wp-statistics/wp-statistics#119]
I know that wp-statistics aims at being a very privacy oriented analytics tool and I suppose this is a big selling point for most of its users. It would therefore be great if issues related to privacy were better documented. I couldn't find any page in the documentation that summarizes precisely which data is up-/downloaded by the plugin to/from which services and whether any settings (apart from the hashing of ip addresses) have any privacy implications.

From skim reading the code and the discussions on the forum, I get the impression that wp-statistics does a great job in terms of privacy. Then why not brag about it on a documentation page? :-)

As an example: I asked myself (and still do not understand this fully) what the consequences of activating or disabling search engines in the settings are and why one is not allowed to disable all search engines. If this setting really just controls which search engines are displayed in the chart, then why is one not allowed to disabled all of them? Also it would be interesting to have information on where and how the plugin stores information, in which format and how this can be accessed by other plugins in a central place. Please consider explaining such things better. Thank you!

**Comment by mostafasoufi** [comment]
Hi @cgogolin,

You've mentioned some good points. We want to know exactly the comments of the user. Let me know if you have a new question so we can all respond to them soon.

**Comment by cgogolin** [comment]
Thanks for coming back to me. Maybe you can start by explaining what the option to disabled search engines actually does and why it is not allowed to disabled all of them.

**Comment by mostafasoufi** [comment]
It's the good think if we add some option in the setting page for disabling Search engines, user agent (Include IP, Browsers and ...)

**Comment by mostafasoufi** [comment]
Added in the v12.3.6 and Privacy & Policy updated.
https://wp-statistics.com/privacy
