### ISSUE TITLE
Opt-Out does not disable tracking / has no effect if IP-hashing is active

### ISSUE THREAD

**Issue by adlerweb** [wp-statistics/wp-statistics#125]
At the moment we've got a way to allow users to "opt-out" ([398](https://github.com/wp-statistics/wp-statistics/blob/master/includes/classes/class-wp-statistics.php#L398)), according to the standard Text this is supposed to affect "[any future tracking](https://github.com/wp-statistics/wp-statistics/blob/e1576d2f58b7ea36f71d8787fb028bb4e0ac6939/includes/classes/class-wp-statistics.php#L762)".

As far as I can see the Cookie however only [hashes the users IP](https://github.com/wp-statistics/wp-statistics/blob/e1576d2f58b7ea36f71d8787fb028bb4e0ac6939/includes/classes/class-wp-statistics.php#L406) but doesn't prevent any other information to be recorded - right? So the plugin is still tracking the user, just not recording the unhashed IP (which results in no change if hashing is enabled globally). Shouldn't at least things like Referrer, User-Agent, etc also be stripped if a no-track-cookie is present?

**Comment by mostafasoufi** [comment]
> As far as I can see the Cookie however only hashes the users IP but doesn't prevent any other information to be recorded - right?

Yes, That's right. Just the hashes IP address enabled in the plugin, because it is one of the GDPR criteria.

**Comment by adlerweb** [comment]
First of all: I am not a lawyer, just repeating things I picked up from other projects:
To be DSGVO/GDP-compliant IPs must always be anonymized when used for tracking/statistics. Additionally users must be able to fully opt-out of the tracking process. For me this sounds like the opt-out should not only enforce hashing but deactivate all recordings as far as possible.

**Comment by mostafasoufi** [comment]
To be more reliable, we can apply this in the next version.

**Comment by cgogolin** [comment]
Ouch. If the information in this bug report is correct then this is a rather serious problem. It is pretty mean to trick your users into thinking they can lawfully use the plugin while in fact they cannot, as the opt out does not actually do what it is supposed to do. This is definitely not an "improvement" but a serious bug and should not be labeled "wontfix".

**Comment by cgogolin** [comment]
I see that there have been a number of updates recently. Has this been resolved so that it is now again possible to use WPStatistics in a GDPR compliant way?

**Comment by mostafasoufi** [comment]
Thank you for your all comments and explanations about this problem. They will be considered in the next versions. We are trying hard to make WP Statistics GDPR compliant as soon as possible. We are going to represent our documents to explain the compliance soon.

**Comment by cgogolin** [comment]
Great that you are looking into this! I am looking forward to using WP-Statistics again once it it GDPR complaint. Please keep this issue open until the problem has actually been resolved, so that other users can see it. Thank you!

**Comment by cgogolin** [comment]
Also it would be good to remove the `nofix` tag, now that you are actually planing to fix this...
