### ISSUE TITLE
BUG: datepicker problem with customized wordpress date format

### ISSUE THREAD

**Issue by renenotheisen** [wp-statistics/wp-statistics#127]
Current situation:
Datepicker default date format is "m/d/Y", the last day of the last year would be displayed: 12/31/2017
here is a example with of last year displayed correct:
![datepicker_manuallpick](https://user-images.githubusercontent.com/39259947/39994724-65cc673c-577a-11e8-837b-cf08705d2bf0.png)

The problem:
We are using this custom date format "F j, Y", the last day of the last year would be displayed; Dezember 31, 2018
As soon as the date is picked with the datepicker calender, the default format will be overriden with our custom format and looks like in this screenshot: 
![grafik](https://user-images.githubusercontent.com/39259947/39995034-6efb1316-577b-11e8-8511-856347025628.png)

When I send the request for the "wrong" date above this response will appear.
![datepicker_calenderpick](https://user-images.githubusercontent.com/39259947/39995331-1dd456fe-577c-11e8-9780-361b6d77f290.png)

Looks like the the parameter will be transformed to our (german) format and can't be processed.

I hope my explantation can help,

**Comment by mostafasoufi** [comment]
@renenotheisen 
Thank you for reporting, Will be fixed in the future.
