### ISSUE TITLE
Opt-out bar is not shown

### ISSUE THREAD

**Issue by cgogolin** [wp-statistics/wp-statistics#132]
**Describe the bug**
The "opt-out" banner is not displayed (in fact it is not even included in the html code). Neither on the mobile, nor on the desktop version. I am experiencing this problem with the OnePress theme but there are several other users reporting the same in the forum:
https://wordpress.org/support/topic/opt-out-message-not-displayed/
https://wordpress.org/support/topic/how-to-use-opt-out/
https://wordpress.org/support/topic/opt-out-dont-work/
https://wordpress.org/support/topic/wp-statistics-opt-out-not-working-on-mobile-devices/

**To Reproduce**
1. Install the plugin.
2. Activate the opt-out option in settings.
3. Observe that no opt-out bar is shown.

**Expected behavior**
The bar at the bottom of the screen is shown and user can opt-out of tracking.

**Desktop (please complete the following information):**
 - OS: irrelevant as the html code is not even generated
 - Browser: irrelevant as the html code is not even generated
 - Version: 12.3.6.1 (the problem was introduced with this version as far as I can tell)

**Smartphone (please complete the following information):**
 - Device: irrelevant as the html code is not even generated
 - OS: irrelevant as the html code is not even generated
 - Browser irrelevant as the html code is not even generated
 - Version: 12.3.6.1 (the problem was introduced with this version as far as I can tell)

**Additional context**
- This is a critical issue as it can have legal repercussions for your users.
- In addition the opt-out should be an actual opt-out: https://github.com/wp-statistics/wp-statistics/issues/125

**Comment by mostafasoufi** [comment]
Hi @cgogolin,

Thank you for all the information, I'll check it on the OnePress theme.

**Comment by mostafasoufi** [comment]
Thank you for explaining this problem. It will be considered in the next versions. We are trying hard to make WP Statistics GDPR compliant as soon as possible. We are going to represent our documents to explain the compliance soon.

**Comment by cgogolin** [comment]
Great that you are looking into this! I am looking forward to using WP-Statistics again once it it GDPR complaint. Please keep this issue open until the problem has actually been resolved, so that other users can see it. Thank you!
