### ISSUE TITLE
no GDPR compliant IP storage

### ISSUE THREAD

**Issue by DanielRuf** [wp-statistics/wp-statistics#133]
The current IP anonymization feature is not really secure or anonymous.

sha1 is already broken / insecure and not recommended at all.

To be GDPR compliant IPs have to be shortened (last bytes are zeroed, IPv4 and IPv6).

https://github.com/wp-statistics/wp-statistics/blob/866902f9e81fe9d37164268bd62283179f8ae603/includes/optimization/wps-optimization.php#L32

https://github.com/wp-statistics/wp-statistics/blob/73f066d51baf54efd989d13c38ee4842141efbc1/includes/classes/class-wp-statistics.php#L395

**Comment by mostafasoufi** [comment]
Hi @DanielRuf,

Have you an alternative the functions?

**Comment by internationils** [comment]
https://www.php.net/manual/en/function.sha1.php
https://www.php.net/manual/en/function.hash.php
use sha256...

**Comment by DanielRuf** [comment]
sha256 can be used but requires bigger fields. What do we have from hashing the IP and useragent? In general the useragent will be frozen in the near future and there may be cases when different users in the same building have the same IP and useragent (for example at work).

Serverside sessions can be used too.
At least ip + useragent is not a unique enough identifier.

NinjaFirewall for example removes the last 3 characters and replaces each of them with a `x`.

**Comment by internationils** [comment]
Then shorten them, and allow to shorten them to /24 and /16 (so 123.231.222.xxx or 123.231.xxx.xxx) and be done with it. I think the redirection plugin does that too. See https://redirection.me/support/privacy-gdpr/ and https://redirection.me/support/options/ ... he just masks the last octet.
I would do that and close this issue. Or make the field bigger, shouldn't be that much more IP address data... 30% or so?

**Comment by DanielRuf** [comment]
Exactly. IPv6 notation is normally not that long as parts can be compressed with `::`.
