### ISSUE TITLE
salt is not really random

### ISSUE THREAD

**Issue by DanielRuf** [wp-statistics/wp-statistics#134]
`rand` is not a CSPRNG, just `random_bytes`

https://github.com/wp-statistics/wp-statistics/blob/866902f9e81fe9d37164268bd62283179f8ae603/includes/optimization/wps-optimization.php#L21

**Comment by mostafasoufi** [comment]
Thank you for the suggestion, We can't use the `random_bytes` because we have a lot of users who are using the PHP v5.4

**Comment by mostafasoufi** [comment]
The size of the library is good and we may have used it.

Thank you.

**Comment by DanielRuf** [comment]
I see no related commit or change.

**Comment by DanielRuf** [comment]
You do not use it, see https://github.com/wp-statistics/wp-statistics/blob/master/composer.json and other files.

**Comment by mostafasoufi** [comment]
Yes, we don't use it till now, because this section will be rewritten :)

**Comment by DanielRuf** [comment]
Ok, thanks for the clarification.
