### ISSUE TITLE
vault press is reporting potential security threats in guzzle help

### ISSUE THREAD

**Issue by chrisDwarner** [wp-statistics/wp-statistics#137]
**Describe the bug**

Vaultpress is reporting a potential security threat in  guzzlehttp plugin.  

Generic.Hidden.Code.2
This file contains suspicious hidden code, and should be checked for recent changes, or malicious code. Often hackers try to hide their hack attempts by obfuscating their attack code, to make it harder to detect. VaultPress has detected a string of suspicious characters in this file. Please check your backup history for recent changes to this file, or contact a Safekeeper if you are unsure.

file: SetCookie.php

  if (preg_match(
380
            '/[\x00-\x20\x22\x28-\x29\x2c\x2f\x3a-**\x40\x5c\x7b\x7d\x7f**]/',
381
            $name)

the scanner is flagging the highlighted text as a potential security threat

**Comment by mostafasoufi** [comment]
https://github.com/wp-statistics/wp-statistics/commit/0ecea8b17283af7d493bdd3379aa775ef69714ea
