### ISSUE TITLE
Vaultpress reporting a PHP.Generic.BadPattern.5 error in guzzleHttp

### ISSUE THREAD

**Issue by chrisDwarner** [wp-statistics/wp-statistics#138]
**Describe the bug**
PHP.Generic.BadPattern.5
This code pattern is often used to run a very dangerous shell programs on your server. The code in these files needs to be reviewed, and possibly cleaned.

file: Middleware.php

232
            return function ($request, array $options) use ($handler, $fn) {
233
                return **$handler($fn(**$request), $options);
234
            };

the hightlighted code was flagged by VaultPress and a security threat by allowing potential remote shell execution.

**Comment by mostafasoufi** [comment]
Fixed. https://github.com/wp-statistics/wp-statistics/commit/0ecea8b17283af7d493bdd3379aa775ef69714ea

Thank you for reporting.
