### ISSUE TITLE
no Opt-out on internet explorer

### ISSUE THREAD

**Issue by Nex4rius** [wp-statistics/wp-statistics#140]
**Describe the bug**
The confirmation message for the Opt-out is not shown on internet explorer.
I've looked into the source code of the page and I cannot see 'div class="wp-statistics-opt-out"' at all.

**To Reproduce**
1. Activate Opt-out
2. Use Internet Explorer

**Expected behavior**
Seeing the Opt-out message.

**Desktop:**
 - OS: Windows 10
 - Browser Internet Explorer 11.165.17134.0
 - Version 12.3.6.4

**Additional context**
This is serious because I'm pretty sure the GDPR law still applies even when you visit a website with Internet Explorer.

**Comment by mostafasoufi** [comment]
Thank you for describing this bug. It will be considered in the next version. Moreover, we are trying hard to make WP Statistics GDPR compliant as soon as possible. We are going to represent our documents to explain the compliance soon.
