### ISSUE TITLE
Mystic number under Opt-Out-DIV

### ISSUE THREAD

**Issue by calli23** [wp-statistics/wp-statistics#142]
When I get the opt-out-message printed on my website, there is also printed a mystic number under that DIV element. The number seems to be something like an ID because it does only change depending on the requested url. See my screenshot from html code:

<img width="356" alt="bildschirmfoto 2018-07-30 um 16 29 24" src="https://user-images.githubusercontent.com/24553863/43403855-7b0346ec-9416-11e8-9a6d-62c250e35c21.png">

After the message was confirmed or denied, the number disappeared. Where does it come from or is this a bug? My research in the source code was not successful.

**Comment by mostafasoufi** [comment]
This feature was added in the previous versions. It's going to be omitted in the next version.
