### ISSUE TITLE
How to exclude site.ru referrer spam?

### ISSUE THREAD

**Issue by Sanookmakmak** [wp-statistics/wp-statistics#146]
I have this in .htaccess:

```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTP_REFERER} site\.ru [NC]
  RewriteRule ^(.*)$ - [F]
</IfModule>
```
but it seems not to work.

I also have excluded site.ru in the "Excluded hosts list", but site.ru is still growing on the referrer statistics page.

How can i exclude it?

Thank you.

**Comment by mostafasoufi** [comment]
Use the `91.109.201.210` IP address on the **Excluded hosts list**.
