### ISSUE TITLE
Notifications: Some options are missing

### ISSUE THREAD

**Issue by clickwork-git** [wp-statistics/wp-statistics#148]
Not all options are shown in the dropdown menu. At the moment for example in some installations "Once a week" is missing.

https://github.com/wp-statistics/wp-statistics/blob/6e4a74f4490a7bd30777e524129c23da4f9b4d03/includes/settings/tabs/wps-notifications.php#L219

**Comment by mostafasoufi** [comment]
You can easily add a new interval schedule by doing the following using the `cron_schedules` filter.

```
 add_filter( 'cron_schedules', 'cron_add_weekly' );
 
 function cron_add_weekly( $schedules ) {
 	// Adds once weekly to the existing schedules.
 	$schedules['weekly'] = array(
 		'interval' => 604800,
 		'display' => __( 'Once Weekly' )
 	);
 	return $schedules;
 }
```

**Comment by clickwork-git** [comment]
Thank you very much!
