### ISSUE TITLE
Como agregar un user_name a la tabla statistics_visitor

### ISSUE THREAD

**Issue by Hernaan** [wp-statistics/wp-statistics#152]
Estoy tratando de agregar un nombre de usuario como un texto simple a mi tabla statistics_visitor, pero no logro hacerlo... ya agregue mi campo en la bd.. paso un pedacito del codigo que hice.. alguna ayuda?

if ( ! $this->result ) {
        //aqui agarro el nombre de usuario logueado
        $user = wp_get_current_user();
        $usuario = $user->user_login;
        $wpdb->insert(
            $wpdb->prefix . "statistics_visitor",
            array(
                'last_counter' => $this->Current_date( 'Y-m-d' ),
                'referred'     => $this->get_Referred(),
                'agent'        => $this->agent['browser'],
                'platform'     => $this->agent['platform'],
                'version'      => $this->agent['version'],
                'ip'           => $this->get_IP(),
                'location'     => '000',
                //aqui es donde lo trato de insertar
                'user_name'    => $usuario,
            )
        );
    }

**Comment by mostafasoufi** [comment]
The content of the issue should be entered in the English.
