### ISSUE TITLE
How to add a user_name to the statistics_visitor table

### ISSUE THREAD

**Issue by Hernaan** [wp-statistics/wp-statistics#153]
I am trying to add a username as a simple text to my table statistics_visitor, but I can not do it ... I already added my field in the database .. I pass a bit of the code I did .. any help?

if ( ! $this->result ) {
//aqui agarro el nombre de usuario logueado
$user = wp_get_current_user();
$usuario = $user->user_login;
$wpdb->insert(
$wpdb->prefix . "statistics_visitor",
array(
'last_counter' => $this->Current_date( 'Y-m-d' ),
'referred' => $this->get_Referred(),
'agent' => $this->agent['browser'],
'platform' => $this->agent['platform'],
'version' => $this->agent['version'],
'ip' => $this->get_IP(),
'location' => '000',
//aqui es donde lo trato de insertar
'user_name' => $usuario,
)
);
}

**Comment by mostafasoufi** [comment]
Related https://github.com/wp-statistics/wp-statistics/issues/206
