### ISSUE TITLE
Count error??

### ISSUE THREAD

**Issue by ThePuterMan** [wp-statistics/wp-statistics#154]
Message at the top of the list of page counts is:

Warning: count(): Parameter must be an array or an object that implements Countable in /home/mayomale/members.mayomalevoicechoir.ie/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-pagination.php on line 464

I have updated to the latest version of the plugin and am running the latest version of WordPress

**Comment by ThePuterMan** [comment]
Does this mean it is fixed?

**Comment by mostafasoufi** [comment]
Fixed in the beta version and will be released soon.
https://github.com/wp-statistics/wp-statistics/archive/development.zip

@ThePuterMan

**Comment by ThePuterMan** [comment]
Many thanks
