### ISSUE TITLE
Excluded Admin Pages disappeared

### ISSUE THREAD

**Issue by arnautorrent** [wp-statistics/wp-statistics#161]
As far as I'm concerned, in the exclusions tab of the settings, in the Site URL Exclusions section it should appear a **Excluded Admin Pages** checkbox between **Excluded login page** and **Excluded RSS feeds**.

<img width="983" alt="captura de pantalla 2018-10-13 a les 13 31 27" src="https://user-images.githubusercontent.com/10051615/46904924-5779bd80-ceec-11e8-82d2-1f845b26f741.png">

**Comment by mostafasoufi** [comment]
Thank you for the reporting, this issue fixed in the beta version and will be resolved in the next version.
