### ISSUE TITLE
(URGENT)!!! If  Anonymize IP Addresses feature enabled, IP location can't be found

### ISSUE THREAD

**Issue by asd91** [wp-statistics/wp-statistics#164]
Hello! If  Anonymize IP Addresses feature enabled, IP location can't be found using GeoIP database as when this feature is enabled, an ip address's last digits i.e. 888.888.888.**888** get's converted to 888.888.888.**000** which is not supported by GeoIP. It can be fixed by converting 888.888.888.**888** to 888.888.888.**0**.

**Comment by mostafasoufi** [comment]
Thank you for reporting, the issue fixed in this commit. https://github.com/wp-statistics/wp-statistics/commit/aab3699e6c63c23a7fc1693623a552c1817f04c7
