### ISSUE TITLE
Check with Cloudflare

### ISSUE THREAD

**Issue by mostafasoufi** [wp-statistics/wp-statistics#168]

**Comment by timabeck1** [comment]
The only thing you need to know is that the overview page just cycles and
never displays stats.  As for the other sections,  I haven't checked yet.

**Comment by timabeck1** [comment]
Here is an image of what I mean for the Overview page:  
![wp-stats](https://user-images.githubusercontent.com/44932115/48318093-7346b100-e5c9-11e8-9c6d-91dc8ef183a1.png)

**Comment by timabeck1** [comment]
As soon as I can get more info, I will

**Comment by mostafasoufi** [comment]
Can you take a screenshot from the console and network (XHR) in the Google Chrome?

**Comment by timabeck1** [comment]
I am not sure what you mean?

**Comment by timabeck1** [comment]
I found out today that the problem with WP-statistics was my fault.   I
had a plugin installed that I should have never used.   Easy HTTPS
Redirect.   I  made some changes and right now all is well.

Tim
