### ISSUE TITLE
New style for Recent Visitors widgets

### ISSUE THREAD

**Issue by mostafasoufi** [wp-statistics/wp-statistics#172]
Current style:

![before](https://user-images.githubusercontent.com/701520/48423403-c3fb0d00-e775-11e8-844b-91228d95ec60.png)

New Style:
![new](https://user-images.githubusercontent.com/701520/48423408-c8272a80-e775-11e8-9596-f7023033e21a.png)

**Comment by MHitMaN** [comment]
Done and added all other things with some fixes on last commit at Development branch.

**Comment by mostafasoufi** [comment]
Thank you.
