### ISSUE TITLE
Avoid using jQuery in the inline script to allow websites to defer jQuery loading

### ISSUE THREAD

**Issue by xuhdev** [wp-statistics/wp-statistics#177]
It should be possible to avoid using jQuery in the inline script, so that websites can defer loading jQuery for faster page loading. See [here](http://youmightnotneedjquery.com/#post) for a possibility to replace the jQuery usage.

**Comment by mehrshaddarzi** [comment]
hi xuhdev,
this is a good idea for faster page load.
Waiting for reviewing developers.

thank you.
