### ISSUE TITLE
WP Statistics not loading

### ISSUE THREAD

**Issue by safhammer2** [wp-statistics/wp-statistics#181]
![screen shot 2018-11-29 at 14 20 20 1](https://user-images.githubusercontent.com/45460285/49228276-e41c0480-f3e2-11e8-8c41-e11daa9d9efd.png)

This is all I get, continuous loading. 

There is this message in at the top:
"GeoIP collection is not enabled. Please go to setting page to enable GeoIP for getting more information and location (country) from the visitor."

Then when I go to the settings of WP Statistics, I see the opening page with various options...BUT when I try to use the menu bar, it does not select any of the menu items at all:

![screen shot 2018-11-29 at 14 32 38](https://user-images.githubusercontent.com/45460285/49228697-d3b85980-f3e3-11e8-9a73-7d2e3071aa59.png)

I have uninstalled it and re-installed it. Same result.
Hope someone can help.

**Comment by abbeygirl2018** [comment]
I have the exact same issue, has this been fixed?

**Comment by safhammer2** [comment]
Still waiting for any response from these guys. Been a while and still the same issue.

**Comment by abbeygirl2018** [comment]
Okay thanks for the heads up..

**Comment by abbeygirl2018** [comment]
I just solved my issue by going back to version 12.5.3, hope that helps.

**Comment by safhammer2** [comment]
Thanks, I'll give it a shot.

**Comment by safhammer** [comment]
The following is the debug log:
[18-Dec-2018 13:06:55 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Ihover_Circular_Image_Hover_Effects::__construct(), 0 passed in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/wp-overlays.php on line 254 and exactly 1 expected in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/classes/ihover-circular-image-hover-effects.php:66
Stack trace:
#0 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/wp-overlays.php(254): Ihover_Circular_Image_Hover_Effects->__construct()
#1 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php(286): WP_Overlays_Pro->hook_in_foot('')
#2 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-admin/admin-footer.php(72): do_action('admin_footer', '')
#5 /cust in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/classes/ihover-circular-image-hover-effects.php on line 66
[18-Dec-2018 13:07:30 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Ihover_Circular_Image_Hover_Effects::__construct(), 0 passed in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/wp-overlays.php on line 254 and exactly 1 expected in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/classes/ihover-circular-image-hover-effects.php:66
Stack trace:
#0 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/wp-overlays.php(254): Ihover_Circular_Image_Hover_Effects->__construct()
#1 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php(286): WP_Overlays_Pro->hook_in_foot('')
#2 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-admin/admin-footer.php(72): do_action('admin_footer', '')
#5 /cust in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-content/plugins/wp-overlays/classes/ihover-circular-image-hover-effects.php on line 66

**Comment by safhammer** [comment]
Unlike the abbeygirl2018, installing the lower version did not make a difference for me.

**Comment by safhammer2** [comment]
Any findings yet?

**Comment by mostafasoufi** [comment]
@safhammer 
It seems that the wp-overlays plugin has interfered. Please disable it.

**Comment by safhammer2** [comment]
Thanks for that. It works BUT now I get this when I try to access my site even as a customer:

Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Illegal offset type in isset or empty in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 75 Warning: Illegal offset type in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php on line 77 Warning: Cannot modify header information - headers already sent by (output started at /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/class-wp-hook.php:75) in /customers/5/0/f/riverviewmanor.co.uk/httpd.www/wp-includes/pluggable.php on line 1223


That's all I see on www.riverviewmanor.co.uk
Please help.
Regards
Saf
