### ISSUE TITLE
add `Edge` Browser to List Browser Detected Plugin

### ISSUE THREAD

**Issue by mehrshaddarzi** [wp-statistics/wp-statistics#188]
add Microsoft `Edge` Browser to List Browser Detected Plugin

```
$user_agent = $_SERVER['HTTP_USER_AGENT']; 
preg_match('/Edge/i', $user_agent)
```

**Comment by mostafasoufi** [comment]
https://github.com/wp-statistics/wp-statistics/commit/51f88aac9348ef36e8e0679f5b2e3237035fce86
https://github.com/wp-statistics/wp-statistics/commit/94485ba6f0fd83abb73f68400f0cfec39cddf7b1
