### ISSUE TITLE
Syntax error on php-5.3 server

### ISSUE THREAD

**Issue by oh2mqk** [wp-statistics/wp-statistics#19]
Wordpress installation on CentOS 6.9 is failing to start after plugin updates. 

[Wed Aug 30 22:19:14 2017] [error] [client 202.46.54.24] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/wp/wp-content/plugins/wp-statistics/wp-statistics.php on line 707

The issue is that on that line there is statement:
>  $plugins = [];

which is fine on PHP 5.4 and after, but CentOS 6 has PHP 5.3.
Working syntax is:
>  $plugins = array();

Please keep the trailing edge alive too.

Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips

**Comment by mostafasoufi** [comment]
Hi @oh2mqk,

This issue fixed in this commit https://github.com/wp-statistics/wp-statistics/commit/d2d9b8671c39aad66e0aa2b4e8bca033c93631c6

Will be released in the WordPress repo soon.
