### ISSUE TITLE
Summaries have stopped displaying visitors, unique visits

### ISSUE THREAD

**Issue by Robdev1** [wp-statistics/wp-statistics#192]
WP Statistics, since Sat. Dec. 29, has stopped displaying the summary of the number of unique visitors and visits (sometimes labelled "hits" in your system).  When I go to the visitors tab, I can see the traffic (browsers, IP address, country etc), so that appears to be working.  But the total number of visitors per day is not being displayed anywhere I can see on the WP Statistics dashboard.

**Comment by mostafasoufi** [comment]
Could you please tell me about your installed plugins?

cc @mehrshaddarzi

**Comment by Robdev1** [comment]
I chased the issue down to a different plugin, an IP/country blocker.  It caused a fair amount of anomalies. Thank you for responding and this item is resolved vis a vis your WP Statistics plugin.
