### ISSUE TITLE
Setting: Statistical reporting - Schedule

### ISSUE THREAD

**Issue by MHitMaN** [wp-statistics/wp-statistics#194]
![2019-01-05_16-19-34](https://user-images.githubusercontent.com/20977558/50724610-bcb50780-1105-11e9-8e99-ab22585372a7.png)
As u can see in the image, we have Some Repeated Schedule in select box and we need the Schedules like this :

- Once Hourly
- Once Daily
- Twice Daily
- One Weekly
- Twice Weekly
- Once Monthly
- Twice Monthly

As u can see in the second image, it is a fresh WordPress installed with plugin Schedule options 
![2019-01-05_16-25-53](https://user-images.githubusercontent.com/20977558/50724694-dc98fb00-1106-11e9-919a-3cdcd4ca3bed.png)

**Comment by W360S** [comment]
Hello, is that issues fixed? im not seeing any update in the module?

**Comment by mostafasoufi** [comment]
Fixed [in here](https://github.com/wp-statistics/wp-statistics/commit/3115ca54aa94b2a7696846c339c773e70f6acef9) and will be released soon.

@W360S

**Comment by W360S** [comment]
should i update git repo or should i wait update?

**Comment by mostafasoufi** [comment]
Please wait for the update from WordPress.org, because the development version is not stable.

**Comment by W360S** [comment]
Thanks 😊
