### ISSUE TITLE
Cache compatibility

### ISSUE THREAD

**Issue by mostafasoufi** [wp-statistics/wp-statistics#196]
This issue created for getting information about cache problem and discuss it.

**For the below plugins, we need help and information to fix the problem**
- [x] LiteSpeed Cache - https://wordpress.org/plugins/litespeed-cache/
- [x] W3 Total Cache - https://wordpress.org/plugins/w3-total-cache/

**Comment by mehrshaddarzi** [comment]
i test W3 Total Cache plugin , there is not problem with wp-statistics

**Comment by mehrshaddarzi** [comment]
![testddf](https://user-images.githubusercontent.com/949491/50823826-1e65b380-134a-11e9-95f7-55ea963014d8.JPG)

i purge all cache from `LiteSpeed Cache plugin` and tested again.
this plugin is compatibility with wp-statistics. :)

**Comment by misiman** [comment]
Hi,

I had already tested the plugin with Purge All and it didn't seem to work. However, my (rough) investigation showed something notable.

After the first wp-json endpoint hit when a (presumably unique) counter is generated like:

wp-json/wpstatistics/v1/hit?_=1546947352

the next hit to the server results in the same URL (including 1546947352) being used.

Also, I tried preventing this behaviour in LiteSpeed > Settings > Excludes but it still happened?

Please make sure you check this with a LiteSpeed server otherwise you will get different results, because LiteSpeed server performs some server level caching.

Thanks

**Comment by mostafasoufi** [comment]
@misiman Could you please give us a WordPress access?
Send to hi@veronalabs.com

**Comment by misiman** [comment]
Hi Mostafasoufi,

How's the investigation going?

**Comment by misiman** [comment]
Hi,

Is anyone working on this?

I've sent several more error reports to hi@veronalabs.com but no-one has replied.

**Comment by mostafasoufi** [comment]
Sorry for the late reply, I'll check and say you soon.
https://github.com/wp-statistics/wp-statistics/milestones

We're involved yo new version of WP-Statistics

**Comment by misiman** [comment]
Hi Mostafasoufi,

Have you made any progress on resolving this?

Thanks

**Comment by mostafasoufi** [comment]
@misiman 
We have an update that required to some change for preparing the cache system.

**Comment by misiman** [comment]
@mostafasoufi 

Any news yet?

**Comment by misiman** [comment]
> @misiman
> We have an update that required to some change for preparing the cache system.

I haven't seen this update and the problem still exists months after being raised.

Please advise if you are going to fix this bug.

Regards

**Comment by karolgrudzinski** [comment]
I installed this plugin on my site a week ago and it recorded visits only on a first day. Today I added **/wp-json/wp-statistics/v2/hit** to LSCache exclusions and WP Statistics registered some visits. I will wait a few days, maybe it fixes this issue.

**Comment by mostafasoufi** [comment]
@karolgrudzinski Good point, don't forget to check out this article which is related to cache troubleshooting
https://wp-statistics.com/resources/troubleshoot-with-cache-plugins/

**Comment by karolgrudzinski** [comment]
After 2 weeks I can say it definitely fixed my issue.
