### ISSUE TITLE
dynamic check to show list post/page select box in wps_statistics_pages

### ISSUE THREAD

**Issue by mehrshaddarzi** [wp-statistics/wp-statistics#199]

**Comment by mehrshaddarzi** [comment]
@mostafasoufi 
Please Test and Closed This item.

**Comment by mostafasoufi** [comment]
It's fine but there is another problem to linking with `page-uri=/page-slug/`. Go to below address and click on Hit of the items

```
/wp-admin/admin.php?page=wps_pages_page
```

It's better the `page-uri=/page-slug/` change to `page-id=153`
