### ISSUE TITLE
Add new columns to users online table

### ISSUE THREAD

**Issue by mehrshaddarzi** [wp-statistics/wp-statistics#203]
Columns:
- [x] `user_id`
- [x] `page_id`
- [x] `type`

Also please consider a new meta box in the overview page as below columns:

|  Country | IP  | Page  | Referrer  | 
|---|---|---|---|
| US  | 192.0.0.0  | [About](http://localhost.com/about)  | [google.com](http://google.com)  |

**Comment by mehrshaddarzi** [comment]
@mostafasoufi 
Done,
Please review and close it.

![031659](https://user-images.githubusercontent.com/949491/51424473-9c944680-1be3-11e9-8af3-93ac472d68e1.JPG)

**Comment by mostafasoufi** [comment]
Great, please change the Current Page title in their meta box to `Users Online`

**Comment by mehrshaddarzi** [comment]
https://github.com/wp-statistics/wp-statistics/commit/49d51c5a0c706a359bfe92b1444df2ad7f4d65a4
