### ISSUE TITLE
Piwik blacklist fails to enable

### ISSUE THREAD

**Issue by Tsuroerusu** [wp-statistics/wp-statistics#225]
I have just installed wp-statistics 12.5.7, and I tried to enable the Piwik blacklist, however after clicking the "Update" button, the options are left disabled, and nothing happens if I try to repeat. I am experiencing this problem on two WordPress sites, one with very tight permissions and SELinux enabled, and the other with very lax permissions where.

**Comment by mehrshaddarzi** [comment]
Hi,
Thanks for this issue.
we solved this Problem and Release in the new version

**Comment by mehrshaddarzi** [comment]
@mostafasoufi 
Please Check and close it.
