### ISSUE TITLE
Plugin stops tracking search engine hits

### ISSUE THREAD

**Issue by lonelydrone** [wp-statistics/wp-statistics#235]
Plugin has not tracked search hits for a while now. Uninstalled/reinstalled etc.

**Comment by mostafasoufi** [comment]
Search Engine Referrals and Words are highly dependent on the search engines providing the information to us. Unfortunately, we can’t do anything about it; we report everything we receive.

**Comment by lonelydrone** [comment]
can you point me at the file and where in that file this is caught and I will try to find the issue. Other plugins seeming are able to record the hit.  TY!
