### ISSUE TITLE
Impossible to set an arbitrary period of time

### ISSUE THREAD

**Issue by kolgenpav** [wp-statistics/wp-statistics#236]
It has become impossible to set an arbitrary period of time for the Pages section of WP Statistics plugin version 12.6. Settings are possible only for predefined periods: 10 days, 20 days, 30 days, 2 months, 3 months, 6 months, 9 months, 1 year, All the time.  This is the issue for the plugin fucntionality.
<img width="800" alt="WP_Statistics_time_period_setting_issue" src="https://user-images.githubusercontent.com/3978552/54072407-01cef480-4283-11e9-9473-3d485b7aed63.PNG">

**Comment by mehrshaddarzi** [comment]
@kolgenpav 

This issue is fixed and will be release soon.
thanks for your report.

commit link : https://github.com/wp-statistics/wp-statistics/commit/d1484894cc7fdbc9c4b450664715dcfdeb9e58eb
