### ISSUE TITLE
The excluded IP address list is not saved

### ISSUE THREAD

**Issue by kolgenpav** [wp-statistics/wp-statistics#237]
The excluded IP address list is not saved. It disappears after Settings-Exceptions page update.
<img width="614" alt="Excluded IP address list" src="https://user-images.githubusercontent.com/3978552/54072614-b36f2500-4285-11e9-93d5-979bea591fca.PNG">

**Comment by mehrshaddarzi** [comment]
@mostafasoufi , @kolgenpav 

watch the video :  
https://www.useloom.com/share/9d3a5ae814244630a62e8149bc656155

Please added (one per line) according to video.

**Comment by kolgenpav** [comment]
I have added the addresses as shown in the video, but the settings are not saved and the exceptions do not work.
<img width="604" alt="stat-1" src="https://user-images.githubusercontent.com/3978552/54228715-67351680-450b-11e9-8015-72d411c4cc24.PNG">
<img width="613" alt="stat-2" src="https://user-images.githubusercontent.com/3978552/54228774-88960280-450b-11e9-8297-ff87056baa3a.PNG">
<img width="177" alt="stat-3" src="https://user-images.githubusercontent.com/3978552/54228785-9055a700-450b-11e9-82ca-0ea19c637f18.PNG">
