### ISSUE TITLE
&amp; on E-mail Name 

### ISSUE THREAD

**Issue by yusha** [wp-statistics/wp-statistics#239]
Hi, My WordPress website title is MyCompany & Co. Now on Settings under Notifications tab I have created a daily notification via email of Statistical reporting. Everything is working fine but when I receive the e-mail it's showing` &amp; ` on the e-mail name beside subject. Can you resolve this on the next update?

**Comment by mehrshaddarzi** [comment]
@mostafasoufi @yusha 

This issue solved and release in next version.

https://github.com/wp-statistics/wp-statistics/commit/d6d112c579818c468f7448d54ec34346c9c506e6

thanks for your report.

**Comment by yusha** [comment]
@mehrshaddarzi &amp; was actually in $blogname not on subject. Did it fixed in your edits?

**Comment by mehrshaddarzi** [comment]
@yusha 
Yes.
I wrote the subject because our development teams are reviewing our code :)

**Comment by yusha** [comment]
Hi after the latest update 12.6.1 it says the Fixed bug to get home page title.
 But looks like it hasn't been resolved. Please see the screenshot for mine below
<img width="863" alt="stats" src="https://user-images.githubusercontent.com/473559/54792444-c0840080-4c03-11e9-80fc-ce664802982e.PNG">

**Comment by yusha** [comment]
> @yusha
> Yes.
> I wrote the subject because our development teams are reviewing our code :)

Please see the issue.. :) @mehrshaddarzi

**Comment by yusha** [comment]
@mostafasoufi the issue hasn’t been resolved. Please keep the status open.
