### ISSUE TITLE
WP Statistic Overview not loading

### ISSUE THREAD

**Issue by PREDAEric** [wp-statistics/wp-statistics#265]
Good Day!

I have a problem in my WP Statistic, all my Visits and visitors goes down, since the update of this plugin, and also everytime i open the wp statistic overview i see this database connection, and keeps loading.

![ERROR](https://user-images.githubusercontent.com/50388329/57343619-a16f0d00-7176-11e9-9771-904187f4c9a8.png)

**Comment by mehrshaddarzi** [comment]
@PREDAEric 

Hi,
This error means that the server database is unable to respond.
In the new version of our plugin, we introduced a new method to reduce this error.
The new version will be released in the next few weeks.

thanks.
