### ISSUE TITLE
Page's title should be encoded or filtering html entities/javascript code

### ISSUE THREAD

**Issue by kuqadk3** [wp-statistics/wp-statistics#271]
I was testing on : 
- Wordpress 5.2.1
- WP Statistic 12.6.5

Account with Editor role can create Post with Title that contain javascript/html. For example : 

`<script>alert(document.cookie)</script>`

![image](https://user-images.githubusercontent.com/12135974/58610016-1c3dca80-82d4-11e9-8edd-145e4559aa9d.png)

WP statistics page that use these title will got affected for xss attack, for example : overviews, pages,...

![image](https://user-images.githubusercontent.com/12135974/58610055-4d1dff80-82d4-11e9-880c-0dbe26156e77.png)

Even if the Editor delete the Post, but it still remain in top 10 page that got most hit, the Overviews page still be affected. So in reality, attacker that controls the Editor account can create page with title that contains maclious javascript code that steal admin cookie (for example), visit it a lot that make it be in top 10 page most visited, delete the post so admin wont notice the weird post that have javascript in title. And when admin click on Overviews page of WP Statistic, his cookie will be stolen.

**Comment by mehrshaddarzi** [comment]
Hi @kuqadk3 
Please change this Line :

https://github.com/wp-statistics/wp-statistics/blob/72f0b644178ec834b5794b8d2d0678bc723ccdd5/includes/functions/functions.php#L1971

to

`
'title'     => esc_html( get_the_title( $page_id ) ),
`

and tell me feedback.

**Comment by kuqadk3** [comment]
WoW. Nice. Quick fix.

That fix the xss in Overview and Pages.

Categories and Author is also affected and still affected. Sorry for not mention them in first place.

**Comment by kuqadk3** [comment]
I think we need to esc_html all those that do $post_obj->post_title

https://github.com/wp-statistics/wp-statistics/search?utf8=%E2%9C%93&q=%24post_obj-%3Epost_title&type=

**Comment by mehrshaddarzi** [comment]
@kuqadk3 
Yes.
We Fixed This issue for next Version.
Thanks a lot.

**Comment by ethicalhack3r** [comment]
Hi! Ryan from wpvulndb.com here.

Do you know when the next version will be released which includes this patch?

We'd like to add the vulnerability to our database, but would prefer to do so once it has been patched.

Thanks!

**Comment by mostafasoufi** [comment]
Hi @ethicalhack3r,

The new version will be released until Friday.
