### ISSUE TITLE
wp-json/wpstatistics/v1/hit api return 400 on my website

### ISSUE THREAD

**Issue by Lostars** [wp-statistics/wp-statistics#298]
plugin version:12.6.8

hit api return 400 and warns that missing _wpnonce and wp_statistics_hit parameter,
but it has the parameter mentioned above,here are the screenshots:
![image](https://user-images.githubusercontent.com/13404175/63563890-52b67900-c595-11e9-908a-8a8acece6efd.png)
![image](https://user-images.githubusercontent.com/13404175/63563954-acb73e80-c595-11e9-9bc4-ce5f398ed2dc.png)
Hope that you can help,thank you !

**Comment by mehrshaddarzi** [comment]
Fixed.
