### ISSUE TITLE
[wpstatistics stat=pagevisits]

### ISSUE THREAD

**Issue by Anticosti** [wp-statistics/wp-statistics#299]
Greetings,

I am using Oxygen Builder (oxygenbuilder.com).
This theme builder let us use conditions to show or hide different types of content.
 
**I was asking on Oxygen support group:**
I use WP Statistics to show on customer's page, the number of hits his page has received with this shortcode: [wpstatistics stat=pagevisits].

How could I configure the conditions to make sure he sees only his own stats and not the ones of the other customers, when browsing others' listings?

**An Oxygen Dev replied:**
I don't find a function provided by the plugin for this at https://wp-statistics.com/2017/05/26/function-api/.

Can you try contacting the plugin dev regarding this?

**So here I am...**
Hope you can help me on this.
Fingers' crossed.

**Comment by mehrshaddarzi** [comment]
Hi @Anticosti 
thanks for saying this problem.
WP-Statistics, not have any WordPress Shortcode for getting the only Own users visitor from a page.
We will try to make this possible in future versions.

**Comment by Anticosti** [comment]
Thank you @mehrshaddarzi
Will be hoping patiently for it to come soon.
Take care! Kindly,

**Comment by ptitou** [comment]
looking for the same functionality with elementor

**Comment by mostafasoufi** [comment]
Hey,

We have something similar for shortcodes and Elementor, but since the priority is low, will work on it after v14.11.

Thanks
