### ISSUE TITLE
Widget translation 

### ISSUE THREAD

**Issue by ceda018** [wp-statistics/wp-statistics#3]
I've tried to translate widget to Bosnian ( Serbian) language, but without success. There wasn't strings form widget.php in .po file. Can you help me please. 

P.S. I've downloaded .po from https://translate.wordpress.org/projects/wp-plugins/wp-statistics

**Comment by ceda018** [comment]
I've managed to update .po file from source code. Widget translated, but those strings are not available at translate.wordpress.org...

**Comment by mostafasoufi** [comment]
I'll check that.
