### ISSUE TITLE
The IPs all display as 127.0.0.1 when I convert the protocol of the website from http to https

### ISSUE THREAD

**Issue by 18612425230** [wp-statistics/wp-statistics#300]
The IPs all display as 127.0.0.1 when I convert the protocol of the website from http to https

**Comment by 18612425230** [comment]
The IPs displayed nomal value such as 14.215.176.139,but when I converted the protocol from http to https, the IPs display as 127.0.0.1, and I do not know whether it is the problem of https. Thank you so much.

**Comment by mehrshaddarzi** [comment]
@18612425230 

Please Check the visitor IP method in the plugin settings page?

**Comment by 18612425230** [comment]
@mehrshaddarzi You are right, in the visitor IP settings page I select the option "Use Custom Header",but my server dose not use the custom key in $_SERVER for getting IP, so it dose not work. I have changed the option to "Use REMOTE_ADDR", it works well. Thank you very much!
