### ISSUE TITLE
Suggestion: Page trend view with total site visitors

### ISSUE THREAD

**Issue by st3phan76** [wp-statistics/wp-statistics#301]
Hi! Using this plugin for some years, I did a small change to a version some months ago. A single page trend is not very meaningful. I thought it would be nicer and more useful when comparing page trends (page-list > visits) with total site visitors in one statitic. 
To get this, I just picked up some lines of code you used somewhere else an I changed `includes/log/page-statistics.php` and `includes/log/widgets/page.php` Of course this only works until the next update and I have to 'hack' these files again.
Perhaps you may find this useful and include it in one of your next editions ... Thanks a lot!

**Comment by mostafasoufi** [comment]
Hello,

Sorry for the late reply. The recent updates have likely resolved your issue. If not, feel free to let us know. Thanks.
