### ISSUE TITLE
Rest API error when using Cache option. 

### ISSUE THREAD

**Issue by itsTheFae** [wp-statistics/wp-statistics#302]
I have been using this plugin on a few sites and have noticed an issue with the Settings page for this plugin.   
When `Use Cache Plugin` option is enabled, the statistics Settings page will check if the Rest API endpoint `wp-json/wpstatistics/v1/hit` is responding and will display a notification on the page as per the logic in `WP_Statistics_Admin::notification_use_cache_plugin()`  but the issue is between the check and the endpoint definition specifically.  

The endpoint check will always fail as it is made using `wp_remote_post()` instead of the `wp_remote_get()` method, and beyond this the endpoint requires a number of parameters which are not given in the test request code.

I added a temporary fix to one installation, as a means of testing out this error.   To fix it I switched the `wp_remote_post` request to a GET request and simply added a less strict route `hittest` that used the same test logic as the original `hit` route but removed the other parameter requirements.

This issue doesn't seem to impact any function of the plugin, it is just confusing to see the error notice in the admin settings screen when everything seems to be working.    

Hopefully this information helps out!

**Comment by mostafasoufi** [comment]
Thank you for reporting, we'll fix this issue in the next version and if you'd like, we are welcome from any PR.

**Comment by mehrshaddarzi** [comment]
@mostafasoufi 
Please check and close this issue.
