### ISSUE TITLE
How secure and How Old

### ISSUE THREAD

**Issue by fastmarketo** [wp-statistics/wp-statistics#304]
How Secure is your Product, and How old is your Product → https://wordpress.org/plugins/wp-statistics/#what%E2%80%99s%20the%20difference%20between%20visits%20and%20visitors%3F

Which Year did you first Launch this?

**Comment by mostafasoufi** [comment]
It's a good question, the first release was from 9 years ago
https://plugins.trac.wordpress.org/log/wp-statistics?limit=100&rev=851241&mode=stop_on_copy

**Comment by fastmarketo** [comment]
Thanks, I will buy Pro Now. You are a very reliable company.

**Comment by mostafasoufi** [comment]
😉

**Comment by fastmarketo** [comment]
By the way, in general, How does one checks Plugins version release in WP repository for any plugin?

**Comment by mostafasoufi** [comment]
Sorry, your question is not clear :)
