### ISSUE TITLE
Ads pulled through non-SSL connection causing browser errors.

### ISSUE THREAD

**Issue by Tsuroerusu** [wp-statistics/wp-statistics#309]
The big purple banner that is being shown in the Overview section of WP Statistics is currently being pulled from a non-SSL URL causing the browser to give an error.

The problem is not in the code itself because the code pulling the add does actually reference an SSL connection.

On line 155 in the file: includes/classes/class-wp-statistics-admin.php
The following URL is used:
`https://wp-statistics.com/wp-json/ads/overview`

However, if I put that URL into my browser, I get the following JSON output:

`{"ID":"variant3","title":"The world's simplest Rank Tracker for SEO","link":"https:\/\/www.wincher.com\/?referer=wp-statistics&adreferer=variant3&utm_source=wp-statistics&utm_medium=banner&utm_campaign=3mo&utm_content=variant3","image":"http:\/\/j.mp\/2QKTbV5","_target":"yes","status":"yes"}`

In here we see the URL:
`http://j.mp/2QKTbV5`

And that is the file that the browser is pulling over a non-SSL connection and thus giving an error.

This should require just a simple server-side fix, and thus requires no bugfix release for WP Statistics. I hope this can be resolved ASAP.

**Comment by mostafasoufi** [comment]
Thank you for reporting, I've converted the ads URL to https method.
