### ISSUE TITLE
WP Statistics with cache and REST ignores exclusions

### ISSUE THREAD

**Issue by zepich** [wp-statistics/wp-statistics#310]
I'm using the plugin in a website together with W3 Total Cache. Everything works fine in general, except that i see my visits and all visits from the bots in the statistics. Since my ip is in the ip exclusion list, the plugin should not count my visits. Also the list with bots is full of bots but i still see Googlebot in example in the statistics.

I've tried to find the problem and i think i found it. In the file includes/classes/class-wp-statitics-hits.php in Line 89, we have an if and since the request is always via REST, the condition is always true. This means that the part with all the exclusions in the else gets never executed.
https://github.com/wp-statistics/wp-statistics/blob/2156039c02baca3e42cc4246ee18510fe7d22718/includes/classes/class-wp-statistics-hits.php#L89

I think i understand why you hahve this if there and for what use case someone could use it. But i think the else is not needed. If we remove the else, it would stop execute the construct if someone sets 'exclude' by REST request. If this parameter is not set, it will continue with the exclusions below like IP, agent and so on.

```php
/* code until line 89 */

if ( WP_Statistics_Rest::is_rest() ) {
	$this->exclusion_match  = ( WP_Statistics_Rest::params( 'exclude' ) == 1 ? true : false );
	$this->exclusion_reason = WP_Statistics_Rest::params( 'exclude_reason' );

	if ( $this->exclusion_match === true ) {
		return;
	}
}

// Detect if we're running an ajax request.
if ( defined( 'DOING_AJAX' ) && DOING_AJAX ) {
	$this->exclusion_match  = true;
	$this->exclusion_reason = 'ajax';
	return;
}

if ( ( defined( 'DOING_CRON' ) && DOING_CRON === true ) || ( function_exists( 'wp_doing_cron' ) && wp_doing_cron() === true ) ) {
/* more code */
```

If you want and if my suggested change is correct, i can prepare a pull request.

**Comment by mostafasoufi** [comment]
Could you review our beta version which is has a lot of improvements?
https://github.com/wp-statistics/wp-statistics/tree/development

**Comment by marcoatfoundry** [comment]
This is still a problem. Tried the newest version from the WP repo (master seems to be the same state as development at the time of writing).
