### ISSUE TITLE
multisite issue

### ISSUE THREAD

**Issue by under-score** [wp-statistics/wp-statistics#311]
I have 4 sites, site #1 and #4 are running nicely, with #2 and #3 I get an error message that I do not understand as I haven't removed anything

![screen](https://user-images.githubusercontent.com/2796454/73964423-7175b580-4912-11ea-8de4-7d17c68bc541.png)

**Comment by mostafasoufi** [comment]
Could you review our beta version which is has a lot of improvements?
https://github.com/wp-statistics/wp-statistics/tree/development

**Comment by under-score** [comment]
sorry, this basically destroyed everything. Deactivated, removed, uploaded, reactivated and reset database with the following result

![Bildschirmfoto 2020-07-05 um 19 26 29](https://user-images.githubusercontent.com/2796454/86540615-12d75680-bf07-11ea-88ca-d4635ad9741d.jpg)

**Comment by mostafasoufi** [comment]
Could you provide us your error log? or you can see the current error through **Inspect > Network > XHR > Response**

**Comment by under-score** [comment]
Do you mean the console?

![Bildschirmfoto 2020-07-05 um 22 03 04](https://user-images.githubusercontent.com/2796454/86541219-80858180-bf0b-11ea-8aa5-c71cd73e8521.jpg)

**Comment by mostafasoufi** [comment]
Thanks, we'll review it.

**Comment by amirfallahii** [comment]
We apologize for the delay in addressing this issue.

Unfortunately, there was a problem with saving the plugin settings in Multisite mode, which we have fixed in the 14.7.2 update.

We appreciate your cooperation and feedback.
