### ISSUE TITLE
Database related error: MariaDB server version for the right syntax to use near '' 

### ISSUE THREAD

**Issue by Aronno1920** [wp-statistics/wp-statistics#314]
I face the query warning... how to solve the following;

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 for query SELECT `page_id` FROM wpfn_statistics_pages WHERE `date` = '2020-04-12' AND `type` = '' AND `id` = made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_Statistics_Rest->hit, WP_Statistics_Hits->Pages

**Comment by mostafasoufi** [comment]
Could you review our beta version which is has a lot of improvements?
https://github.com/wp-statistics/wp-statistics/tree/development
