### ISSUE TITLE
GeoIP not working anymore

### ISSUE THREAD

**Issue by Rustimation** [wp-statistics/wp-statistics#315]
Ever since the People at Maxmind have changed their download policy (arounf Jan 1st 2020), the GeoIP Functions don't work anymore. The Update Buttons lead to a critical error, a manual install of GeoIPLite is not possible/not obvious.

**Comment by mostafasoufi** [comment]
This issue fixed in the beta version and is available in the `development` branch, please try to test it and let us know about the result of your test.

**Comment by Rustimation** [comment]
Installed Development version fom Dec 22: Klicking on the update button in "Settings/Externals" results in a critical error:
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 295 der Datei /var/www/wordpress/wp-content/plugins/wp-statistics-development/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php verursacht. Fehlermeldung: Uncaught RuntimeException: The gmp or bcmath extension must be installed to read this database. in /var/www/wordpress/wp-content/plugins/wp-statistics-development/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php:295
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/wp-statistics-development/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(131): MaxMind\Db\Reader\Decoder->decodeUint(']\xEF\xB4\xED', 4)
#1 /var/www/wordpress/wp-content/plugins/wp-statistics-development/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(97): MaxMind\Db\Reader\Decoder->decodeByType(9, 64204338, 4)
#2 /var/www/wordpress/wp-content/plugins/wp-statistics-development/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(220): MaxMind\Db\Reader\Decoder->decode(64204338)
#3 /var/www/wordpress/wp-content/plugins/wp-statistics-development/includes/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(104): MaxMind\Db\Reader\Decoder->decodeMap(9, 64204336)
#4 /v

As Maxmind now requires a login/License key, I don't think the current beta will help to fix the problem. Or is there a tab where I can enter my Maxmind License Key? But maybe I'm simply doing something wrong. Any ideas?
thanks Chris aka Rustimation

**Comment by mostafasoufi** [comment]
Could you review our beta version which is has a lot of improvements?
https://github.com/wp-statistics/wp-statistics/tree/development

**Comment by sanderlv** [comment]
Hello, I have uploaded the latest version as advised above. I have also increased the php max mem on server side to 512M and as well on the file wp-config.php:
/** Memory Limit */
define('WP_MEMORY_LIMIT', '512M');

But keep getting:
![image](https://user-images.githubusercontent.com/16528916/103929393-8c056f80-511d-11eb-88de-1307b2297f12.png)

i cannot enable it.

What is wrong?

**Comment by mostafasoufi** [comment]
Did you try in `WP_DEBUG` mode? is there any error in error_log? @sanderlv

**Comment by sanderlv** [comment]
How do I do that?

WP_DEBUG

**Comment by mostafasoufi** [comment]
I mean debug mode
https://wordpress.org/support/article/debugging-in-wordpress/

**Comment by sanderlv** [comment]
Sorry, i do not know wehre and how to start debugging this.
1. what and where do I need to enable debug in WP? And where will I have to look at it?
2. Where is the error_log?

**Comment by mostafasoufi** [comment]
Enabling debug mode cause to show the currents error on the screen, you can open wp-config.php and enable this line

```
define('WP_DEBUG', true);
```

The error_log is located in your WordPress root
