### ISSUE TITLE
Update of WP Statistics seem to failed, plugin deleted

### ISSUE THREAD

**Issue by Alek2077** [wp-statistics/wp-statistics#316]
I tried updating the plugin yesterday, but it got deleted immediately afterwards, with this message showing up everywhere:
https://i.imgur.com/hvfLAe8.png

When I click it, nothing happens. Contacted DreamHost and they assured me all the files are in my WP installation, but the plugin is still not there:
https://i.imgur.com/xb5HzXB.png

Didn't have the time do anything else. Didn't want to restore any backups or change anything, not to mess anything up, and I'd like to know what happened, if possible, and how to prevent this from happening again.

**Comment by mostafasoufi** [comment]
Delete the wp-statistics plugin manually from your server and then try to install the plugin again.

It might the plugin directory It has locked.
