### ISSUE TITLE
Database Error...

### ISSUE THREAD

**Issue by Aronno1920** [wp-statistics/wp-statistics#318]
Hi, I'm seeing the following error form several weeks. It may help you.

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 for query SELECT `page_id` FROM wpfn_statistics_pages WHERE `date` = '2020-05-02' AND `type` = '' AND `id` = made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_Statistics_Rest->hit, WP_Statistics_Hits->Pages

Thanks

**Comment by mostafasoufi** [comment]
Thank you for reporting, try to disable the plugin and then enable it to rebuild some columns.

**Comment by Aronno1920** [comment]
I check the issue after disable then enable the plugins. I also delete all old data. But not solved yet.

**Comment by mostafasoufi** [comment]
Could you review our beta version which is has a lot of improvements?
https://github.com/wp-statistics/wp-statistics/tree/development
