### ISSUE TITLE
WP Statics not working with Elementor 

### ISSUE THREAD

**Issue by kpkirankp** [wp-statistics/wp-statistics#319]
I am able to add the 'Statistics' in my elementor frame work UI.
But when i enable some statistics and click on 'Apply' it never gets saved or even none of the values are getting popup in the elementor. Is there any problem for statistics to work with elementor? I am using free version of elementor and not a pro version. I am using the latest version of WP stat.

**Comment by mostafasoufi** [comment]
Could you review our beta version which is has a lot of improvements?
https://github.com/wp-statistics/wp-statistics/tree/development
