### ISSUE TITLE
WP statistic bug?

### ISSUE THREAD

**Issue by orzheznitskiy** [wp-statistics/wp-statistics#320]
WP statistic shows

GeoIP collection is disabled due to the following reasons:
    * GeoIP collection requires the cURL PHP extension and it is not loaded on your version of PHP!

but Ubuntu 20.04 says its loaded.
Is it a bug?
Thanks

**Comment by mostafasoufi** [comment]
The plugin checks the curl through `function_exists('curl_init')`

To make sure about that, you can see the curl status with `phpinfo();`
