### ISSUE TITLE
Duplicate key in purging / syntax error in logging?

### ISSUE THREAD

**Issue by WGroleau** [wp-statistics/wp-statistics#323]
I turned on debugging for an error in another plug-in, and I see that I am getting MANY errors like this:

`[05-Sep-2020 06:23:19 UTC] WordPress database error Duplicate entry '1' for key 'page_id' for query INSERT INTO `wp_statistics_historical` (`value`, `category`, `uri`, `page_id`) VALUES ('21', 'uri', '//', '1') made by do_action_ref_array('wp_statistics_dbmaint_hook'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Statistics_Schedule->dbmaint_event, wp_statistics_purge_data`

Many different IDs: 1, 297, 283, 0, …

Also, many of the following:

`[08-Sep-2020 18:42:24 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 for query SELECT `page_id` FROM wp_statistics_pages WHERE `date` = '2020-09-08' AND `type` = '' AND `id` =  made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_Statistics_Rest->hit, WP_Statistics_Hits->Pages`

**Comment by mostafasoufi** [comment]
Hi,

We've made several performance and optimizations in the latest release that should resolve the issue you reported. Please update your software to the latest version and check if the problem persists.

Best
