### ISSUE TITLE
Huge differences in the number of visitors

### ISSUE THREAD

**Issue by VivianaBruno** [wp-statistics/wp-statistics#324]
Hi, 
After the last update the number of visitors went down. But in another plugin in the same webpage the level of visitors is between the normal average, I attach two screenshots.  
Thanks!

![Screenshot from 2020-09-08 18-45-50](https://user-images.githubusercontent.com/40771022/92531010-e3451300-f203-11ea-8147-824bd48e0922.png)
![Screenshot from 2020-09-08 18-45-24](https://user-images.githubusercontent.com/40771022/92531013-e4764000-f203-11ea-970e-762210db39c0.png)

**Comment by mostafasoufi** [comment]
Hello,

We've recently published an article that addresses several key factors impacting data accuracy in WP Statistics. This guide provides insights and enhancements for more accurate data collection. You can read the full article here: [Enhancing Data Accuracy](https://wp-statistics.com/resources/enhancing-data-accuracy/).

Best
