### ISSUE TITLE
trim() and strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Fabioni** [wp-statistics/wp-statistics#328]
trim() expects parameter 1 to be string, array given
strlen() expects parameter 1 to be string, array given
at
wp-content/plugins/wp-statistics/includes/settings/tabs/wps-visitor-ip.php:48

**Comment by Fabioni** [comment]
similar to #321

**Comment by mostafasoufi** [comment]
Thank you for reporting the issue, we are going to take a look at the functionality which use in that section.
