### ISSUE TITLE
problem while upgrading

### ISSUE THREAD

**Issue by sq5bpf** [wp-statistics/wp-statistics#332]
problem when upgrading from 13.0.1 to 13.0.2. wordpress 5.5.3, other installed plugins: wp globus, aryo activity log, classic editor. very standard install, no customizations.

[Sun Nov 29 17:12:03.871895 2020] [php7:error] [pid 22498] [client x.x.x.x:60648] PHP Fatal error:  Uncaught Error: Class 'WP_Statistics_Updates' not found in /www/_deleted_.com/htdocs/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-welcome.php:78\nStack trace:\n#0 /www/_deleted_.com/htdocs/wp-includes/class-wp-hook.php(287): WP_Statistics_Welcome::do_welcome(Object(Plugin_Upgrader), Array)\n#1 /www/_deleted_.com/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)\n#2 /www/_deleted_.com/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n#3 /www/_deleted_.com/htdocs/wp-admin/includes/class-plugin-upgrader.php(371): do_action('upgrader_proces...', Object(Plugin_Upgrader), Array)\n#4 /www/_deleted_.com/htdocs/wp-admin/includes/ajax-actions.php(4452): Plugin_Upgrader->bulk_upgrade(Array)\n#5 /www/_deleted_.com/htdocs/wp-includes/class-wp-hook.php(287): wp_ajax_update_plugin('')\n#6 /www/_deleted_.com/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)\n#7 /www/_deleted_.com/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n in /www/_deleted_.com/htdocs/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-welcome.php on line 78, referer: https://_deleted_.com/wp-admin/plugins.php

edit: on the wp statistics overview screen i get "Problem Connect to WordPress RestAPI." under most headers ("hit statistics", "top 10 pages" etc)

**Comment by sq5bpf** [comment]
it seems that uBlock origin firefox plugin blocks the 13.0.2 plugin from displaying statistics. it displays the graphs corectly when this is disabled:

https://wordpress.org/support/topic/problem-connect-to-wordpress-restapi/

i still would consider this a bug:
- it did work with 13.0.1
- many people use adblockers

**Comment by mostafasoufi** [comment]
Thank you for providing us the useful log, that's fixed in this commit https://github.com/wp-statistics/wp-statistics/commit/0bad2d7a638a5e021dfdc9d223f2786aca620a1e and will release tonight.
