### ISSUE TITLE
Error type E_ERROR 

### ISSUE THREAD

**Issue by avegit** [wp-statistics/wp-statistics#334]
I got an error-message from Wordpress and my site is not available from mobile devices using browser with the chrome engine. Please try: https://buechernarr.org/

My Wordpress-Version:
WordPress-Version 5.5.3
Aktuelles Theme: Tortuga (Version 2.1.1)
Aktuelles Plugin: WP Statistics (Version 13.0.2)
PHP-Version 7.4.8

Error-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 78 der Datei /home/www/home/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-welcome.php verursacht. Fehlermeldung: Uncaught Error: Class 'WP_Statistics_Updates' not found in /home/www/home/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-welcome.php:78
Stack trace:
#0 /home/www/home/wp-includes/class-wp-hook.php(287): WP_Statistics_Welcome::do_welcome(Object(Plugin_Upgrader), Array)
#1 /home/www/home/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /home/www/home/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/www/home/wp-admin/includes/class-plugin-upgrader.php(371): do_action('upgrader_proces...', Object(Plugin_Upgrader), Array)
#4 /home/www/home/wp-admin/update.php(51): Plugin_Upgrader->bulk_upgrade(Array)
#5 {main}
 thrown

==== END

Yes, its german, but I think its nevertheless understandable.

Regards
Frank

**Comment by mostafasoufi** [comment]
Thank you for providing us the useful log, that's fixed in this commit 0bad2d7 and will release tonight.
