### ISSUE TITLE
"Problem Connect to WordPress RestAPI."

### ISSUE THREAD

**Issue by rollo27** [wp-statistics/wp-statistics#335]
On some sites with WP 5.5.3 using different themes and different sets of plugins, all dashboard widgets of wp-statistics are throwing the message "Problem Connect to WordPress RestAPI.", and not showing any data.

**Comment by mostafasoufi** [comment]
The issue has been fixed in this commit https://github.com/wp-statistics/wp-statistics/issues/332 and will release soon.
