### ISSUE TITLE
Visitors and hits issue + error

### ISSUE THREAD

**Issue by mhm2006** [wp-statistics/wp-statistics#336]
Online and total Visitors low than actual even low than the search engines referrals and hits not correct  after updating to 13.0.2 beside i got the below error
BR,

Error Details
=============
An error of type E_ERROR was caused in line 78 of the file /home/u560608005/domains/mysite.com/public_html/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-welcome.php. Error message: Uncaught Error: Class ‘WP_Statistics_Updates’ not found in /home/u560608005/domains/mysite.com/public_html/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-welcome.php:78
Stack trace:
#0 /home/u560608005/domains/mysite.com/public_html/wp-includes/class-wp-hook.php(287): WP_Statistics_Welcome::do_welcome(Object(Plugin_Upgrader), Array)
#1 /home/u560608005/domains/mysite.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/u560608005/domains/mysite.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/u560608005/domains/mysite.com/public_html/wp-admin/includes/class-plugin-upgrader.php(371): do_action(‘upgrader_proces…’, Object(Plugin_Upgrader), Array)
#4 /home/u560608005/domains/mysite.com/public_html/wp-admin/includes/ajax-actions.php(4452): Plugin_Upgrader->bulk_upgrade(Array)
#5 /home/u560608005/domains/mysite.com/public_html/wp-includes/class-wp-hook.php(287): wp_ajax_update_plugin(”)
#6 /home/u560608005/do

**Comment by orangenschalen** [comment]
I can confirm the same problem with WP- Statistics 13.0.3, on WP 13.0.3 and PHP 7.3.10.

The website sends out an e-mail with a notice of the error, but the hosted page itself seems to work without obvious trouble at least.
