### ISSUE TITLE
WP Statistics runs only on PHP 7.2+

### ISSUE THREAD

**Issue by DanielRuf** [wp-statistics/wp-statistics#339]
It seems you forgot to build the project with composer with the correct PHP version.
You've built it with PHP 7.2 and so many users can not access their website anymore due to the following:

https://plugins.trac.wordpress.org/browser/wp-statistics/trunk/includes/vendor/composer/platform_check.php

![grafik](https://user-images.githubusercontent.com/827205/100738656-3202e300-33d6-11eb-96af-58a9614c61fe.png)

![grafik](https://user-images.githubusercontent.com/827205/100738697-4646e000-33d6-11eb-8218-22d5645b8fcf.png)

It seems the new build did not use the latest change regarding the platform checks: https://github.com/wp-statistics/wp-statistics/commit/056d4850cc705ebc0f220eca33cfa39ead871431

By the way, composer and vendor folder should not be used like this for WordPress plugins. Please scope the dependencies. For scoping the dependencies I can provide you a list of recommended tools / packages for this.

**Comment by DanielRuf** [comment]
@mostafasoufi you should check that and provide a quick release as automatically updated WordPress instances are now basically broken.

**Comment by mostafasoufi** [comment]
Hey @DanielRuf 

I've built it with the PHP v5.6 to make sure all packages follow this version and not greater than that version.

https://github.com/wp-statistics/wp-statistics/commit/b87a426c3c0d028ec9a8859833ccc0a50552aaf2

**Comment by DanielRuf** [comment]
> Hey @DanielRuf
> 
> I've built it with the PHP v5.6 to make sure all packages follow this version and not greater than that version.
> 
> [b87a426](https://github.com/wp-statistics/wp-statistics/commit/b87a426c3c0d028ec9a8859833ccc0a50552aaf2)

Well, as you can see it is clearly not the case (see also the reviews and topics on wordpress.org which mention the same). Please try your plugin on a WordPress instance with PHP 7.1. The platform check still throws the error.

I can do a short test in a few minutes.

**Comment by DanielRuf** [comment]
> I've built it with the PHP v5.6 to make sure all packages follow this version and not greater than that version.
> 
> [b87a426](https://github.com/wp-statistics/wp-statistics/commit/b87a426c3c0d028ec9a8859833ccc0a50552aaf2)

Ok, so I guess there will be an update today? Because the latest version 13.0.3 is broken due to this.

**Comment by mostafasoufi** [comment]
I'll try to test the recent commits and then going to release the new version. hopefully will finish Tonight. @DanielRuf

**Comment by mostafasoufi** [comment]
I've had a new commit https://github.com/wp-statistics/wp-statistics/commit/446609d5887286902bde2badb6787c0b90bb52fd regarding the composer, I've just deleted the vendor and ran the `composer install` to get the fresh files and packages as well. could you please review that and let me know everything looks fine? @DanielRuf

**Comment by mostafasoufi** [comment]
I think all good, I'm going to release the new version.

Best

**Comment by PeterPablo** [comment]
For all those having a broken WordPress instance due to not running on the latest php. If you receive this message (posted here not as a screenshot, so internet searches can lead here) `Your Composer dependencies require a PHP version ">= 7.2.0". You are running xxx` you can **unbreak** your homepage/blog by (temporarily) editing the following file `platform_check.php`, which is located in the following relative path of your instance `./wp-content/plugins/wp-statistics/includes/vendor/composer/platform_check.php`:
You need to delete, save and upload the php check, which is defined by lines 7-9:
```
if (!(PHP_VERSION_ID >= 70200)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 7.2.0". You are running ' . PHP_VERSION  .  '.';
}
```

I hope this helps others who were caught by surprise and wondered how to easily restore operation (without jumping through the hoops of looking for a recent backup, etc.).

Best regards
