### ISSUE TITLE
SQL Error in pages that does not have ID

### ISSUE THREAD

**Issue by massacration** [wp-statistics/wp-statistics#341]
I have some pages does not have ID, pages made by plugins and custom taxonomies that doesn't have ID, and it causes errors everytime the plugin try to get Statistics in those pages.

Is there any way to fix it?

```
2020/12/02 21:54:50 [error] 630366#630366: *89800 FastCGI sent in stderr: "PHP message: Erro de banco de dados do WordPress You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 para a consulta SELECT `page_id` FROM wp_statistics_pages WHERE `date` = '2020-12-02' AND `type` = '' AND `id` =  feita por require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_Statistics_Rest->hit, WP_Statistics_Hits->Pages" while reading response header from upstream, client: 172.69.70.93, server: localhost, request: "GET /blog/wp-json/wpstatistics/v1/hit"
```

**Comment by mostafasoufi** [comment]
Weird, where did you exactly get this error? from the front side or the admin side? is there any more information or maybe a screenshot of that table?

**Comment by Luke-SF** [comment]
> Weird, where did you exactly get this error? from the front side or the admin side? is there any more information or maybe a screenshot of that table?

It had everything except for that first column. Upon trying to add a hit entry.
