### ISSUE TITLE
What is ~ used for?

### ISSUE THREAD

**Issue by movibeast** [wp-statistics/wp-statistics#342]
I am seeing `“~”` before the search word in the statistics.
What is it used for? what does it means. In almost all of the `“~”` related word. it is the page title.
Does it means that googe/bing like bot scrapped the site or Something else

**Comment by movibeast** [comment]
no response, huh

**Comment by mostafasoufi** [comment]
There is an option in the setting page to disable it, please take a look at the setting page.
