### ISSUE TITLE
Ghost visitors

### ISSUE THREAD

**Issue by wiizarrrd** [wp-statistics/wp-statistics#345]
Hi,

in the last month I got many ghost visitors, that are listed. Those make up more than 95% of the visitors of my webseite. If I look at what page those ghost visitors visited, there is nothing displayed ("-"). 

It would already help, if I could filter for the page in the tab "visitors".

Thank you :)

**Comment by mostafasoufi** [comment]
Hello,

We've recently published an article that addresses several key factors impacting data accuracy in WP Statistics. This guide provides insights and enhancements for more accurate data collection. You can read the full article here: [Enhancing Data Accuracy](https://wp-statistics.com/resources/enhancing-data-accuracy/).

Best
