### ISSUE TITLE
some problems on new version

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#346]
Hi Team 
These problems are in the latest version of the plugin (13.0.5) and the latest version of WordPress 5.6:

The width of the column of views on pages, posts, etc. is very large and takes up a lot of space
https://s17.picofile.com/file/8421409576/wpstatics.png

When the slugs are in Persian, they are not displayed correctly in the statistics
https://s16.picofile.com/file/8421409626/wpstatics1.png

Not all filters are displayed correctly on the filters screen, and the zoom must be reduced to display correctly
https://s17.picofile.com/file/8421409642/wpstatics2.png

In the overview page, by changing the filter for the year, month or week, the text below it does not change and the last visits are fixed in the last 20 days.
https://s17.picofile.com/file/8421409684/wpstatics3.png
...........................................................
این مشکلات در نسخه آخر افزونه (13.0.5) و آخرین نسخه وردپرس 5.6 وجود دارد:
عرض ستون بازدید ها در صفحات، پست ها و ... بیسیار زیاد شده است و فضای زیادی رو اشغال کرده 
https://s17.picofile.com/file/8421409576/wpstatics.png

زمانی که اسلاگ ها و لینک ها به فارسی ثبت شده باشد در آمارها به صورت صحیح نمایش داده نمی شود
https://s16.picofile.com/file/8421409626/wpstatics1.png

در صفحه فیلتر ها تمام فیلتر های انتهایی از کارد خارج می شود و به درستی نمایش داده نمی شود و برای نمایش صحیح باید زوم رو کاهش داد
https://s17.picofile.com/file/8421409642/wpstatics2.png

در صفحه مرور کلی با تغییر فیلتر سال، ماه یا هفته نوشته زیر آن تغییری نمیکند و دایم آخرین بازدید ها در ۲۰ روز گذشته را نشان میدهد 
https://s17.picofile.com/file/8421409684/wpstatics3.png

**Comment by mostafasoufi** [comment]
Thank you for reporting the issues and providing the screenshots from the issue, we're going to fix all of them for the next version.

Best

**Comment by Sinapars** [comment]
Thank you for the recent update, in the latest version (13.0.6) problem one and two (The width of the column and slugs) were fixed.
But there are still two problems that I hope will be solved in future versions

And one problem that has arisen (of course, I'm not sure it's related to this version, maybe it already exists) is that in the trend page, which above shows a graph of the top 5 page in a certain time period, just the page traffic statistics. Shows the home and the statistics of the other pages are displayed as zero, if we enter the details page of the statistics of that page, we see that there was a visit
Thank you for considering this issue as well
https://s17.picofile.com/file/8424965468/wpstatics4.png
https://s17.picofile.com/file/8424965484/wpstatics5.png

ممنون از شما برای بروزرسانی اخیر , در ورژن آخر ( 13.0.6) مشکل یک و دو (نمایش ستون ها و اسلاگ ها) برطرف شد 
اما دو مشکل بعدی هنوز وجود داره که امیدوارم در ورژن های بعدی حل بشه 

و یه مشکلی که به وجود اومده (البته مطمئن نیستم مربوط به این ورژن باشه شاید از قبل وجود داشته) اونم اینه که در صفحه نمایش بازدید برگه ها، یک نمودار وجود دارد که 5 برگه برتر در بازه زمانی خاصی رو نشون میده اما فقط آمار بازدید صفحه خانه رو نشون میده و آمار بقیه صفحات رو صفر نمایش میده در صورتی که اگر وارد صفحه جزئیات آمار اون صفحه بشیم میبینیم که بازدید وجود داشته 
ممنون میشم برررسی این موضوع رو هم مدنظر داشته باشید

**Comment by amirfallahii** [comment]
Hi @Sinapars 

We apologize for the delay in addressing this issue.

We have reviewed the problem you described and have taken steps to address it.
The latest version of the plugin includes these fixes, and we encourage you to update your installation.

Please let us know if you continue to experience any issues, and we will be happy to investigate further.

We appreciate your feedback and your patience as we work to improve the plugin's functionality.
Best regards,
