### ISSUE TITLE
WP Statistics does not work with WP Super Cache

### ISSUE THREAD

**Issue by mopongo** [wp-statistics/wp-statistics#347]
When using WP Super Cache together with the latest WP Statistics, I observe fewer visitors being counted. The "Cache Enabled" option is set, the permalinks have been updated multiple times and the cache was also cleared. This behaviour makes WP Statistics pretty useless.

I guess the problem is related to https://github.com/wp-statistics/wp-statistics/issues/312, which describes the caching of the `_wpnonce` as root cause. Not sure why that issue was closed without comment.

I appreciate any help or fix for this issue. Thanks.

**Comment by Ploupoz** [comment]
Hi, same issue. If I export the visitors table, the nomber of lines (equal to the number of real visitors) is good but the total is in my case 10 times more important. Thank you for any help. I got the same configuration with WP super cache. Thanks for any help

**Comment by mostafasoufi** [comment]
Hi, Thank you for reporting, I'll review the issue myself and will let you know guys.
