### ISSUE TITLE
Update still failing

### ISSUE THREAD

**Issue by metalguru69** [wp-statistics/wp-statistics#350]
Have had to disable this plugin as it causes the following error on any page in my site:-
Fatal error: Uncaught Error: Call to undefined method MaxMind\Db\Reader::getWithPrefixLen() in /var/sites/s/stdominicstone.org.uk/public_html/wp-content/plugins/wp-statistics/includes/vendor/geoip2/geoip2/src/Database/Reader.php:246 Stack trace: #0 /var/sites/s/stdominicstone.org.uk/public_html/wp-content/plugins/wp-statistics/includes/vendor/geoip2/geoip2/src/Database/Reader.php(217): GeoIp2\Database\Reader->getRecord('Country', 'Country', '81.107.210.28') #1 /var/sites/s/stdominicstone.org.uk/public_html/wp-content/plugins/wp-statistics/includes/vendor/geoip2/geoip2/src/Database/Reader.php(90): GeoIp2\Database\Reader->modelFor('Country', 'Country', '81.107.210.28') #2 /var/sites/s/stdominicstone.org.uk/public_html/wp-content/plugins/wp-statistics/includes/class-wp-statistics-geoip.php(184): GeoIp2\Database\Reader->country('81.107.210.28') #3 /var/sites/s/stdominicstone.org.uk/public_html/wp-content/plugins/wp-statistics/includes/class-wp-statistics-exclusion.php(378): WP_STATISTICS\GeoIP::getCountry() #4 /var/sites/s/st in /var/sites/s/stdominicstone.org.uk/public_html/wp-content/plugins/wp-statistics/includes/vendor/geoip2/geoip2/src/Database/Reader.php on line 246
There has been a critical error on this website.

Learn more about troubleshooting WordPress.

**Comment by mostafasoufi** [comment]
I've already fixed this issue in the related commit, can you please test it?
https://github.com/wp-statistics/wp-statistics/archive/refs/heads/development.zip

**Comment by metalguru69** [comment]
Sorry I'm unable to download that zip

**Comment by mostafasoufi** [comment]
Sorry, use this link
https://codeload.github.com/wp-statistics/wp-statistics/zip/refs/heads/development

**Comment by metalguru69** [comment]
Still failing, same error.

**Comment by mostafasoufi** [comment]
I've uploaded on the Dropbox
https://www.dropbox.com/s/y6vygdl0bv0olzw/wp-statistics.zip?dl=0

**Comment by metalguru69** [comment]
Tried your upload but it still fails exactly the same.  Don't bother sending any more I have changed which one I use.
