### ISSUE TITLE
Geo ip checkboxes changes are not  working after saving on the page 

### ISSUE THREAD

**Issue by halfdanox** [wp-statistics/wp-statistics#351]
It should be saved after clicking on the checkboxes

![vvvaaaa](https://user-images.githubusercontent.com/18633974/111829844-2257cd80-88e5-11eb-851c-b2aec2c17c4b.jpg)

**Comment by mostafasoufi** [comment]
Hi,

Please make sure this folder already exists and has the write permission

```
wp-content/uploads/wp-statistics
```

You can also download the GeoIP DBs manually, just download them from the below repositories and extract them on that path:

https://github.com/wp-statistics/GeoLite2-Country
https://github.com/wp-statistics/GeoLite2-City
