### ISSUE TITLE
Update failed after upgrading WordPress to 5.7

### ISSUE THREAD

**Issue by lisamaco** [wp-statistics/wp-statistics#352]
[WP Statistics Update Failed.pdf](https://github.com/wp-statistics/wp-statistics/files/6185471/WP.Statistics.Update.Failed.pdf)

**Comment by mostafasoufi** [comment]
That's totally weird! can you delete the plugin and install the latest version of plugin manually?

**Comment by lisamaco** [comment]
Yes, that worked. I guess I should have thought of that. Thanks for your help
