### ISSUE TITLE
Problem with update 13.0.8

### ISSUE THREAD

**Issue by webmul** [wp-statistics/wp-statistics#353]
hy, 
this morning, i've doing the update and i have this message on my production site : 
![Extensions wp-statistic](https://user-images.githubusercontent.com/81799417/113392577-a5712d00-9395-11eb-90fc-7fea63970216.jpg)
when i've refresh the page, the problem disapear and the new version was installed.

before, i'he tested on my test website and there were no problems.

thanks

**Comment by mostafasoufi** [comment]
Hi,

This occurs when you are going to update to gather than v12, please remove the plugin and try to install the latest version manually.

Best
