### ISSUE TITLE
WordPress Statistics

### ISSUE THREAD

**Issue by dr-alireza-bahrami** [wp-statistics/wp-statistics#354]
The WP statistics plug-in hasn't been downloaded anymore; Since an incomplete download of it occurred. And the alert is : 

Installation failed: Destination folder already exists.

**Comment by mostafasoufi** [comment]
Please remove the plugin manually in the wp-content directory, then try to install it again manually, should be fine with this way.

**Comment by dr-alireza-bahrami** [comment]
🙏🙏

Sent from my iPhone

On Apr 24, 2021, at 11:59 AM, Mostafa Soufi ***@***.***> wrote:

﻿

Please remove the plugin manually in the wp-content directory, then try to install it again manually, should be fine with this way.
