### ISSUE TITLE
Statistics plugin causing an interface/ui bug in the page and post editor

### ISSUE THREAD

**Issue by seangrogan** [wp-statistics/wp-statistics#355]
I posted this problem in the WP.org support forums : https://wordpress.org/support/topic/i-cant-edit-or-add-hyperlink-in-the-page-editor/

I am having a hard time describing this via text only, so I took a cell phone video trying to do what I want to do:

https://1drv.ms/v/s!Ar9o2aOSoHVPiYlyVqKlcGhCWXppKw?e=qjxTWm

It looks like when I try and edit a hyperlink the button flashes ‘off’ so I can’t click it. I get a similar bug when trying to add a link, although I was able to click it between flashes

WordPress Version 5.7.1; Google chrome Version 90.0.4430.93 (Official Build) (64-bit) — tried with both my extensions on and off (safe mode). It happens in Microsoft Edge and Firefox (which I don’t use regularly, but I imagine they are relatively the latest versions)

I am 99% sure it's the plugin and only this plugin as enabling it alone seems to cause the error (as well as being enabled with all my other plugins), but these are the other info about the site:

* template : 2016
* Enlighter - Customizable Syntax Highlighter
* Imsanity
* TablePress
* MathJax-LaTeX

All these I keep updated to the latest version when pushed

**Comment by mostafasoufi** [comment]
Please try to disable this option **Settings » General » Hits Metabox Chart**

btw, that video was super useful! thanks
