### ISSUE TITLE
wp-statistics.log generated in root directory resulting in potential information disclosure vulnerability

### ISSUE THREAD

**Issue by MeatyFresh** [wp-statistics/wp-statistics#358]
The `wp-statistics.log` file is being generated in the root directory of the site in some circumstances, and is viewable by anonymous visitors in most server configurations by visiting something like `domain.tld/wp-statistics.log`. This potentially leads to a fairly beign but potentially severe (depending on the site) information disclosure vulnerability as site visitors IP addresses can often be logged into this file in the following way:

`1970-01-01 00:00:00 :: The address x.x.x.x is not in the database.`

Ideally this file would be stored not in the root directory of the site and protected to prevent viewing by anonymous visitors. A potential, though ugly, fix I've seen in another plugin is for the file to be a `.php` file with `<?php exit; ?>` on the first line, therefore blocking the file from view.

Personally, I have modified .htaccess to block access to the file.

As an aside, please generate a [Security Policy](https://github.com/wp-statistics/wp-statistics/security) to help people know how to report security issues in wp-statistics.

**Comment by mostafasoufi** [comment]
The problem is evidently not very good, as it appears it was forgotten to fix, despite the fact that I always watch that.

I'll move it to the upload directory with a protection feature so the public won't be able to access it.

Thanks!

**Comment by mostafasoufi** [comment]
I've just fixed the issue on the above commit and going to close the issue, the new version will be released probably on the weekend.
