### ISSUE TITLE
Schedule for GeoIP database update with wrong date

### ISSUE THREAD

**Issue by ghost** [wp-statistics/wp-statistics#363]
If I enable the “Schedule monthly update of the GeoIP database”, the date of the next update always is set as “03/01/1970 @ 16:40” (the hour may change on the two sites, but the date always is January 1970). The database update doesn’t seem to run.

If it can help, the scheduled update of the referral spam blacklist shows the correct date and runs as expected.

Thank you.

![wpstats-day](https://user-images.githubusercontent.com/88327855/127870744-5090f023-1d16-4b60-be21-82c5d4d109b8.png)

**Comment by mostafasoufi** [comment]
Have you ever manually updated the GeoIP? if not, please do that and let me know about the result.

**Comment by mostafasoufi** [comment]
So, I assume the issue had been solved. isn't it?

**Comment by frges** [comment]
Sorry, the database can be updated manually, but the scheduled update doesn't seem to work.

(Anyway, it's not a big deal if the scheduled GeoIP database update doesn't work, as updating it is not really important, as long as it can be initially downloaded...)

**Comment by raumi22** [comment]
Same error here.

**Comment by mostafasoufi** [comment]
Can you please run the purpose event with this plugin? @raumi22 
https://wordpress.org/plugins/wp-crontrol/

I just wanted to make sure the event functionality works fine.

**Comment by mostafasoufi** [comment]
Hello,

This section is already refactored in #563 

Best
