### ISSUE TITLE
Report email not being sent

### ISSUE THREAD

**Issue by frges** [wp-statistics/wp-statistics#364]
I have noticed that the report email with statistics doesn’t seem to be send. I have set it to be sent weekly.

I have checked the list of cron schdules using the plugin WP Crontrol, and the “weekly” schedule exists (the predefined WordPress schedule). The “wp_statistics_report_hook” event exists (although it says “No action”) and it is scheduled to run weekly…

But somehow, the message is not sent. Is there some way to find the cause?

**Comment by mostafasoufi** [comment]
Weird, would you be able to perform the following actions?

1. Deactive the WP-Statistics
2. Delete the WP-Statistics's cronjobs by WP-Crontrol
3. Active the WP-Statistics

**Comment by mostafasoufi** [comment]
Good to hear! I think then it's fine, but we'll improve this section a little bit more later.
