### ISSUE TITLE
Cannot open Customizer: "PHP Warning: Trying to access array offset on value of type bool"

### ISSUE THREAD

**Issue by Nevsor** [wp-statistics/wp-statistics#366]
If this plugin is active and I try to open the theme customizer I get 29 error messages like:

```
PHP Warning: Trying to access array offset on value of type bool in <WP_DIR>\wp-content\plugins\wp-statistics\includes\class-wp-statistics-widget.php on line <LINE_NUMBER>. 
```

where <WP_DIR> is the directory where wordpress is installed and <LINE_NUMBER> is every line number in `form()` in class-wp-statistics-widget.php where a field of `$widget_options` is accessed.

I believe the error is due to `WP_STATISTICS\Option::get('widget')` returning `false`, because the option "widget" does not exist. wp-admin/options.php shows many options beginning with "widget_", but no option named "widget".

I had this problem with two different themes. If I deactivate WP Statistics, the theme customizer works fine.

Wordpress version: 5.8
PHP version: 8.0.9
OS: Windows Server 2012
WP Statistics version: 13.0.9

**Comment by mostafasoufi** [comment]
Thank you for reporting the issue, I've just fixed this issue, hope would be fine. https://github.com/wp-statistics/wp-statistics/commit/f85326bebac3b689b3892007c2c3ddfcac3e01fd
