### ISSUE TITLE
Is there any option to view time-on-site metrics in this wordpress plugin?

### ISSUE THREAD

**Issue by saleemkce** [wp-statistics/wp-statistics#384]
I'd like to see timeonsite tracker JS [https://github.com/saleemkce/timeonsite](https://github.com/saleemkce/timeonsite) integrated in this plugin so that I can view time on page and time on site metrics accurately for each page by user sessions.

This request is based on the fact that the tracker is free to consume on non-production sites, personal blogs etc. and it nicely integrates with PHP/MySql/MariaDB stack and since the backend can be uploaded to WP as is when required. [https://github.com/saleemkce/visual](https://github.com/saleemkce/visual) repo path: visual\backend\php

Following are the steps to integrate this library on any website:
1, Integrate the tracker with script tag
`<script src="https://cdnjs.cloudflare.com/ajax/libs/timeonsite/1.2.0/timeonsitetracker.min.js"></script>`
2, Initiate with some default params in web-page
```
var config = {
    trackBy: 'seconds',
    developerMode: true,
    request: { // presence of request object denotes that data is to be saved in local storage and processed on subsequent page access
        url: 'http://localhost/visual/php/timeonsite.php', // repoint it to your PHP backend data save URL
        headers: [
            // optional headers if any
        ]
    }
};
```
3, Upload the backend code to WP uploads: visual\backend\php Then, navigate to URL http://localhost/visual/index.html to view the time on site metric reports.

Can **_wp-statistics_** provide some automation on this part so that users will be benefited by this plugin?

**Comment by amirfallahii** [comment]
Hi,

We apologize for the delay in responding. 

Thank you for sharing this request with us. Currently, our development team is working on improving and adding new features to the plugin.

Please allow us to work on this feature over this period and integrate it into the plugin in the best possible way.

We appreciate your feedback and your patience as we work to improve the plugin's functionality.
Regards,
