### ISSUE TITLE
Undefined index: HTTP_HOST 

### ISSUE THREAD

**Issue by schmerold** [wp-statistics/wp-statistics#385]
Our logs are filling up with:
Undefined index: HTTP_HOST in /sites/a.org/files/wp-content/plugins/wp-statistics/includes/class-wp-statistics-helper.php on line 98

WP Statistics Version 13.1.2

**Comment by mostafasoufi** [comment]
I assume that might be occures in on the CLI mode, the commit might fix it somehow.

**Comment by mostafasoufi** [comment]
I assume that might occur in the CLI mode, the commit might fix it somehow.
