### ISSUE TITLE
Statistics sent by email are empty

### ISSUE THREAD

**Issue by Sanookmakmak** [wp-statistics/wp-statistics#387]
I have setup to send statistics per email but the reports are always empty.

What is missing?

**Comment by mostafasoufi** [comment]
Have you entered something in the **Message Body**?

<img width="911" alt="Screen Shot 2021-12-23 at 9 56 35 PM" src="https://user-images.githubusercontent.com/701520/147279043-59888da5-818b-4d8a-95fc-1e9f54bb4724.png">

**Comment by Sanookmakmak** [comment]
Thank you, i just forgot to fill in the contents of the report.

;-)
