### ISSUE TITLE
Does this plugin work with WP-Optimize installed?

### ISSUE THREAD

**Issue by craigconstantine** [wp-statistics/wp-statistics#389]
By looking at this graph, can you guess when I installed WP-Optimize? :)

<img width="1242" alt="Screen Shot 2022-01-10 at 10 18 43" src="https://user-images.githubusercontent.com/2278992/148790614-20eff7b9-22fe-4b3e-b253-54e858196f48.png">

Yes, latest everything. Yes, "Cache Compatibility" is enabled. Yes, I did what the instructions say, after flipping this on.

<img width="1170" alt="Screen Shot 2022-01-10 at 10 18 58" src="https://user-images.githubusercontent.com/2278992/148790674-bcc943cc-1510-4cf7-947d-19f655ab7414.png">

Thoughts?

**Comment by mostafasoufi** [comment]
It should be, what's your website address?

**Comment by craigconstantine** [comment]
https://constantine.name/

**Comment by mostafasoufi** [comment]
The HTTP request goes well to the backend which means the stats submits in DB, I assume the dashboard is cached and the problem will be solved by clearing the cache.

**Comment by craigconstantine** [comment]
I don't see how caching would do that. The image of page-views/visitors on the dashboard does update each day that I look at it... anyway, here's the caches cleared, and no change:

<img width="1463" alt="Screen Shot 2022-01-11 at 08 13 22" src="https://user-images.githubusercontent.com/2278992/148948952-55fb43da-5a7c-4e92-b6df-ef62400215fc.png">

**Comment by mostafasoufi** [comment]
This is totally weird indeed. does it count your hits? and also did you check the error log in this path? `wp-content/uploads/wp-statistics/debug.log`

**Comment by craigconstantine** [comment]
> This is totally weird indeed. does it count your hits?

 ¯\_(ツ)_/¯  how would I tell that?

> did you check the error log in this path? wp-content/uploads/wp-statistics/debug.log

there's nothing in that directory (aside from an .htaccess file)

**Comment by mostafasoufi** [comment]
> how would I tell that?
I mean test your hits in Incognito browsing.

>there's nothing in that directory (aside from an .htaccess file)
Are you using the latest version of the plugin? if yes, please create that file manually.

**Comment by craigconstantine** [comment]
Chrome Incognito — the "Overview Summary" display of Visitors and Visits increases by one.

>  if yes, please create that file manually.

Do you mean create the `.htaccess` file manually? okay, I can do that. What would you like me to put into that per-directory access control file?

**Comment by mostafasoufi** [comment]
No, I mean the log file. create this file `wp-content/uploads/wp-statistics/debug.log` and give write permission to the file.

**Comment by craigconstantine** [comment]
I created (chmod 0666) the debug.log file yesterday. 24+ hours and it's still zero size.

**Comment by retroluxfilm** [comment]
Same issue with WP Super Cache since I installed that. It couts way less users that before. Similar to the view posted here.  The Incognito mode works and counts)

**Comment by mostafasoufi** [comment]
I'd prefer to make sure the website is calling the Hit API request properly, take a look at this article. https://wp-statistics.com/resources/troubleshoot-with-cache-plugins/

**Comment by retroluxfilm** [comment]
Yes that is working as it should be. I still get visitors that seem valid but way less that before using the WP Super Cache plugin. I will investigate it further to see if the caching plugin does something else that caused a reduction of visitors.

**Comment by mostafasoufi** [comment]
Hello,

Please update to version 14.9.3. The request method has been switched from GET to POST to avoid any caching issues. This update is fully compatible with WP-Optimize.

Best
