### ISSUE TITLE
woocommence product category page is not show in statistics

### ISSUE THREAD

**Issue by Boytobeaman** [wp-statistics/wp-statistics#390]
I use woocommence with wp-statistics, the product category page is not shown in dashboard when I visit it.

For example:
the product category is
https://www.plastic-crates.com/product-category/collapsable-box/
when I visit it, it is **not shown** in wp-statistics dashboard

But the products of the category  is shown, for example:
https://www.plastic-crates.com/product/cheap-plastic-folding-crate-zjkn604022w-3/

**Comment by mostafasoufi** [comment]
Actually, the plugin is not supported WooComerce stats

**Comment by Boytobeaman** [comment]
Hi @mostafasoufi ,I like this plugin very much, As I understand, the product category page is also a page, do we plan to support it in the future?

**Comment by mostafasoufi** [comment]
Not entirely sure, maybe in the future
