### ISSUE TITLE
PHP Notice:  Trying to access array offset on value of type bool in 

### ISSUE THREAD

**Issue by aydinowicz** [wp-statistics/wp-statistics#392]
https://github.com/wp-statistics/wp-statistics/blob/bb1fe6a89eb582c4f883a1618d6be49f75e04599/includes/class-wp-statistics-widget.php#L251

needed to add the below code after line 251 to fix an array access error that I mentioned [here](https://wordpress.org/support/topic/trying-to-access-array-offset-on-value-of-type-bool-22/)

```
 if (!is_array($widget_options)) {
            return;
        }
```

**Comment by mostafasoufi** [comment]
Thank you for reporting, fixed in https://github.com/wp-statistics/wp-statistics/commit/faa7cc74a6580e9e9005e290762464a3d7bb666b

**Comment by mostafasoufi** [comment]
Seems the ignores the showing the form in the widget, let's fix it by `isset()` @rezataheri94

**Comment by mostafasoufi** [comment]
The issue is fixed by the latest related commit.
