### ISSUE TITLE
deactivate to work in Elementor

### ISSUE THREAD

**Issue by brancatog** [wp-statistics/wp-statistics#393]
I use Elementor to edit my WP site, currently version 3.5.6. I have to deactivate the WP Statistics plugin to edit any page in the site?

let me know if you can help here.

Thanks,
Gary

**Comment by mostafasoufi** [comment]
Hi Gray,

I guess the **Hits Metabox Chart** caused the issue, please check it out by disabling that option in **Settings > General > Hits Metabox Chart**

**Comment by brancatog** [comment]
This option is not enabled in my settings.

**Comment by brancatog** [comment]
There is no error message.

when i go to edit a page, the elementor menu on the left side stays dim
constantly loading.

see attached.
