### ISSUE TITLE
Trigger a report when new visitor

### ISSUE THREAD

**Issue by Alban-mlg** [wp-statistics/wp-statistics#398]
Hello, 
I would like to know if there is a way to trigger a report when a new visitor is on the site? 
I know I might get spammed if there is a lot of traffic on the site but I'm fine with that! 

Thanks ! :)

**Comment by mostafasoufi** [comment]
Hi,

This can be done by action `wp_statistics_save_visitor`, something like this:

```
add_action('wp_statistics_save_visitor', function ($visitor_id, $visitor, $page_type) {
    $schedule = new \WP_STATISTICS\Schedule();
    $schedule->send_report();
}, 10, 3);
```

You can also extend and customize the email report by using the same functionality of `send_report()`
