### ISSUE TITLE
broken hyperlink of external links (a missed ":")

### ISSUE THREAD

**Issue by saeed1922** [wp-statistics/wp-statistics#4]
Hi,
I just wanted to inform you about an annoying bug in your awesome wp-statistics add-on which has not fixed in your recent updates. It seems you have missed a ":" in hyperlinks of (last visitors) and (last searched keywords) which makes the hyperlink unreadable for the web browser (something like "https//www.google.com"). Please see the attached image. I'm not sure if this bug is on other parts of your code too or not.

Kind regards,
Saeed

![statistics-bug](https://user-images.githubusercontent.com/26106115/29003172-08cb0f24-7ac7-11e7-952e-daa3457cf5d8.png)

**Comment by mostafasoufi** [comment]
Will be released Soon.

Thank you for reporting that.
