### ISSUE TITLE
Top 5 Trending Pages still not working

### ISSUE THREAD

**Issue by Hummelpups** [wp-statistics/wp-statistics#400]
Hey there 🙂

The Top 5 Trending Pages Chart is still not working. technically it is working but doesnt use the most trending pages. The table below is correct.

This problem was already discussed here https://wordpress.org/support/topic/pages-top-page-trends-not-working/ but was closed for replies.

Im using v13.1.7, v13.1.15 and latest v13.2.3

Thank you really much

<img width="1261" alt="Bildschirmfoto 2022-06-09 um 08 50 21" src="https://user-images.githubusercontent.com/16844537/172783189-4b781ce2-23cd-4e83-ac50-ff3e5b19abfe.png">
!

**Comment by Hummelpups** [comment]
The problem lies in the function wp_statistics_get_top_pages in template-functions.php.
There is a request for the 5 most visited pages but the function retrieves the 5 last urls without taking viewcount into consideration in the first place.

**Comment by Hummelpups** [comment]
`/**
 * Get top Pages between Time
 *
 * @param null $rangestartdate
 * @param null $rangeenddate
 * @param null $limit
 * @param null $post_type
 * @return array
 */
function wp_statistics_get_top_pages($rangestartdate = null, $rangeenddate = null, $limit = null, $post_type = null)
{
    global $wpdb;

    if($limit != null){
        $splice_limit = $limit;
    }else{
        $splice_limit = 5;
    }
    $limit = null;

    // Get every unique URI from the pages database.
    if ($rangestartdate != null && $rangeenddate != null) {
        $result = $wpdb->get_results($wpdb->prepare("SELECT `uri`,`id`,`type` FROM " . \WP_STATISTICS\DB::table('pages') . " WHERE `date` BETWEEN %s AND %s GROUP BY `uri`" . ($limit != null ? ' LIMIT ' . $limit : ''), $rangestartdate, $rangeenddate), ARRAY_N);
    } else {
        $result = $wpdb->get_results("SELECT `uri`,`id`,`type` FROM " . \WP_STATISTICS\DB::table('pages') . " GROUP BY `uri`" . ($limit != null ? ' LIMIT ' . $limit : ''), ARRAY_N);
    }

    $total = 0;
    $uris  = array();

    // Now get the total page visit count for each unique URI.
    foreach ($result as $out) {
        //Prepare item
        list($url, $page_id, $page_type) = $out;

        // Check if item is of specific post type (string or part of an array) or if post type is set to null
        if (is_null($post_type) || get_post_type($page_id) == $post_type || (is_array($post_type) && in_array(get_post_type($page_id), $post_type))) {
            // Increment the total number of results.
            $total++;

            //Get Page Title
            $page_info = Pages::get_page_info($page_id, $page_type);
            $title     = mb_substr($page_info['title'], 0, 200, "utf-8");
            $page_url  = $page_info['link'];

            // Check age Title if page id or type not exist
            if ($page_info['link'] == "") {
                $page_url = path_join(get_site_url(), $url);
                $id       = WP_STATISTICS\Pages::uri_to_id($out[0]);
                $post     = get_post($id);
                if (is_object($post)) {
                    $title = esc_html($post->post_title);
                } else {
                    if ($out[0] == '/') {
                        $title = get_bloginfo();
                    } else {
                        $title = '';
                    }
                }
            }

            //Check Title is empty
            if (empty($title)) {
                $title = '-';
            }

            // Add the current post to the array.
            if ($rangestartdate != null && $rangeenddate != null) {
                $uris[] = array(
                    urldecode_deep($out[0]),
                    wp_statistics_pages('range', $out[0], -1, $rangestartdate, $rangeenddate),
                    $page_id,
                    $title,
                    $page_url,
                );
            } else {
                $uris[] = array(urldecode_deep($out[0]), wp_statistics_pages('total', $out[0]), $page_id, $title, $page_url);
            }
        }
    }

    // If we have more than one result, let's sort them using usort.
    if (count($uris) > 1) {
        usort($uris, array('\WP_STATISTICS\Helper', 'compare_uri_hits'));
    }

    array_splice($uris, $splice_limit);

    return array($splice_limit, $uris );
    // return array($total, $uris);
}`

**Comment by Hummelpups** [comment]
<img width="1226" alt="Bildschirmfoto 2022-06-09 um 10 29 27" src="https://user-images.githubusercontent.com/16844537/172801914-6391390a-38ea-4951-b092-3f51366b13aa.png">

**Comment by mostafasoufi** [comment]
Hi @Hummelpups 

Thank you for opening the issue and providing the fixed function. Could you please submit a PR? In addition.

Additionally, I'm going to assign this issue to the appropriate person to review it.

**Comment by Hummelpups** [comment]
I have no clue how to do that, sorry

**Comment by mostafasoufi** [comment]
No worry will do that ourselves.

**Comment by mostafasoufi** [comment]
> https://paste.ofcode.org/dLDzUC2KQNgAWiHVeYTunX

Seems this link is not available, can you please send the code here?

**Comment by Hummelpups** [comment]
Hey, i already made a PR #402 and i think it already got accepted and merged

**Comment by mostafasoufi** [comment]
Oh cool, thank you!
