### ISSUE TITLE
Like it but now failing 

### ISSUE THREAD

**Issue by xnabca** [wp-statistics/wp-statistics#401]
rest-api and flushing issue. May not be a wp-statistics problem directly though.
Here is an error associated with Connecting WordPress Rest API Please Flushing rewrite rules or activate WordPress REST API for performance WP-Statistics Plugin Cache

**Comment by elmarkr** [comment]
I experience the same issue

**Comment by mostafasoufi** [comment]
Hi,

Can you send your WordPress URL? we need to make sure the REST API works fine, the REST API should be something like this:

https://yourdomain.com/wp-json/wp-statistics/v2/hit

**Comment by xnabca** [comment]
Https://laurna.com

**Comment by xnabca** [comment]
I can create a temporary admin account for you

**Comment by xnabca** [comment]
Screen shot
![image](https://user-images.githubusercontent.com/107393604/175761853-4016da85-af39-42ec-bf7f-465516175f87.png)

**Comment by mostafasoufi** [comment]
Please send a WordPress access to hi@veronalabs.com, we need to check something.
