### ISSUE TITLE
WP rest API error

### ISSUE THREAD

**Issue by elmarkr** [wp-statistics/wp-statistics#403]
Hey there,
Since the last wordpress update (V6.0) the WP statistics plugin gives a unable to connect to wordpress rest api. Is there any easy way to fix this?

**Comment by mostafasoufi** [comment]
Hi,

Can you send your WordPress URL? we need to make sure the REST API works fine, the REST API should be something like this:

https://yourdomain.com/wp-json/wp-statistics/v2/hit

**Comment by elmarkr** [comment]
https://www.videofabrique.nl

https://www.videofabrique.nl/wp-json/wp-statitics/v2/hit

**Comment by elmarkr** [comment]
> It seems the plugin REST API endpoint is not registered, did you flush the permalinks? you can do that by pressing the **"Save Changes"** on the **Settings > Permalinks**

Thanks for your reply. Of course I have tried this. The notification banner in my wp admin adviced me to do so.

**Comment by mostafasoufi** [comment]
So, please disable and enable the plugin again, and also, can you send your activated plugins? most likely one plugin is disabled the endpoint.

**Comment by elmarkr** [comment]
> So, please disable and enable the plugin again, and also, can you send your activated plugins? most likely one plugin is disabled the endpoint.

I have tried all of that already. I have disabled ALL plugins and reactivated one-by-one. Yours resulted in the error.

**Comment by mostafasoufi** [comment]
The endpoint is registered, https://www.videofabrique.nl/wp-json/wp-statistics/v2/hit

https://capture.dropbox.com/HTYHlFikBCsuzRsF
https://capture.dropbox.com/82huGv35epa0CHWJ

But seems the request failed and faced a 403 error, do you use the security plugin? can you check your server error log? apache/Nginx maybe? because this returns from the web server.

**Comment by elmarkr** [comment]
![screencapture-videofabrique-nl-wp-admin-plugins-php-2022-06-28-11_02_26](https://user-images.githubusercontent.com/108127648/176139455-74007d3c-b03d-4954-b62b-e66ae30838d5.png)
[error_log.txt](https://github.com/wp-statistics/wp-statistics/files/8999460/error_log.txt)

**Comment by mostafasoufi** [comment]
Ask your server support to disable this rule on your webserver modsecurity

```
ModSecurity:  [file "/etc/httpd/conf/modsecurity.d/rules/tortix/modsec/10_asl_rules.conf"] [line "523"] [id "340165"] [rev "292"] [msg "Atomicorp.com WAF Rules: Uniencoded possible Remote File Injection attempt in URI (AE)"] [data "/wp-json/wp-statistics/v2/hit?***] [severity "CRITICAL"] Access denied with code 403 (phase 2). Pattern match "=(?:ogg|tls|ssl|gopher|file|data|php|zlib|zip|glob|s3|phar|rar|s(?:sh2?|cp)|dict|expect|(?:ht|f)tps?)://" at REQUEST_URI. [hostname "www.videofabrique.nl"] [uri "/wp-json/wp-statistics/v2/hit"] [unique_id "YqsWi1QSHvQ17fB4DW9o4QAAAIM"], referer: https://www.videofabrique.nl/wp-json/wp-statistics/v2/hit?***
```

**Comment by elmarkr** [comment]
Hi!
My hostingprovider says it cannot disable the specific rule because it would jeopardise the safety of other websites. It's a shared hosting service.

**Comment by mostafasoufi** [comment]
Alright, we'll do some tweaks to overcome this role on the plugin for the next version and will probably ask you to test it on your WordPress.
