### ISSUE TITLE
URL parameter error in platform statistics

### ISSUE THREAD

**Issue by g4rf** [wp-statistics/wp-statistics#407]
_WP Statistics actual version with actual WordPress version_

On the page Plattform Statistics `/wp-admin/admin.php?page=wps_platform_page` is an URL parameter error when I try to change the date. If I use the links (`10 days`, `20 days` etc.) everything works fine. If I hit the date button, the page shows a no-access message. The reason is simple: The parameter `page` gets the wrong value: instead of `wps_platform_page` it is `wps_platforms_page` with an additional s.

**Comment by g4rf** [comment]
The same for **Browser Statistics** `/wp-admin/admin.php?page=wps_browser_page`. Here it is instead of `wps_browser_page` an additional **s** in `wps_browsers_page`.

**Comment by mostafasoufi** [comment]
That's our fault! thank you for reporting!

The issue has been fixed in the development version and the new version will be released soon.
