### ISSUE TITLE
Referrers page shows always all hits regardless of the date range

### ISSUE THREAD

**Issue by g4rf** [wp-statistics/wp-statistics#408]
On the Referrers page `/wp-admin/admin.php?page=wps_referrers_page` it has no effect on the hit count if I change the date range. It always shows the all time count.

Despite of this, the shown referrers and the order changes if I change the date range. So internally it filters as aspected, only the hit number ist incorrect.

**Comment by mostafasoufi** [comment]
Thank you for reporting the issue! we've just fixed it in this commit https://github.com/wp-statistics/wp-statistics/commit/50f21f247ce593dbb2099ff5c792230bc93748cd
