### ISSUE TITLE
HTTP 500 on Android Chrome with activated plugin

### ISSUE THREAD

**Issue by Florian-Thake** [wp-statistics/wp-statistics#411]
If I activate the plugin on my page, I get an HTTP 500 always on the first load from any Android Chrome Browser. Page can be reloaded, then it works. Clicking on any internal link on the page leads to HTTP 500 again. Reload helps again.

Reproduced on 3 Smartphones with activated plugin. When I deactivate the plugin it works normal.

On Windows with Firefox and Edge it is not reproducible. 

Plugin Version: 13.2.5
Wordpress Version: 6.0.2
PHP: 7.4.30

**Comment by Florian-Thake** [comment]
Ok, sorry, I fixed it by myself by increasing the memory limit of php from 32MB to 64 MB.

I think it would be great if you add a big red banner somewhere with a hint that the default settings will cause this error. 
The bad on this thing is, that it happen only on mobile and not on desktop. So, when you detect it, its probably too late and you dont have a clue whats going on.

**Comment by mostafasoufi** [comment]
HI @Florian-Thake 

Good point, thank you for reporting and opening the issue! In the case of memory limits, we will definitely consider adding a new notice.

Best
