### ISSUE TITLE
Feature request: Show a big warning if php has too low memory limit.

### ISSUE THREAD

**Issue by Florian-Thake** [wp-statistics/wp-statistics#412]
I ran into this issue: 
_"If I activate the plugin on my page, I get an HTTP 500 always on the first load from any Android Chrome Browser. Page can be reloaded, then it works. Clicking on any internal link on the page leads to HTTP 500 again. Reload helps again.

Reproduced on 3 Smartphones with activated plugin. When I deactivate the plugin it works normal.

On Windows with Firefox and Edge it is not reproducible."_

Then I solved it by increasing php memory limit from 32 MB to 64 MB.

The bad on this thing is, that it happen only on mobile and not on desktop. So, when you detect it, its probably too late and you dont have a clue whats going on.

So, I think it would be great if you add a big red banner somewhere with a hint that the default settings will cause this error and a warning message if the php memory limit is too low.

**Comment by mostafasoufi** [comment]
Hey @Florian-Thake,

I will plan to add the notice since it might help users to resolve the issue when they encounter it.

Thank you for the feedback!

**Comment by mostafasoufi** [comment]
Hi,

This is already added here https://github.com/wp-statistics/wp-statistics/blob/master/includes/admin/class-wp-statistics-admin-notices.php#L204-L211

Best
