### ISSUE TITLE
Data overview page is blank

### ISSUE THREAD

**Issue by Doraemonsan** [wp-statistics/wp-statistics#413]
After wp-statistics plug-in is enabled, all charts are blank with light bands swept from left to right，I saw some errors in the console and nginx log, but I don't know how to fix this error，please help me
These are debugging information：
- nginx log：2022/09/09 20:32:46 [error] 13998#0: *2053 directory index of "/home/www/WordPress/wp-json/wp-statistics/v2/metabox/" is forbidden, client: ********, server: ********,
request: "GET /wp-json/wp-statistics/v2/metabox/?name=summary&_=1662726767554 HTTP/2.0", host: "********", referrer: "https://********/wp-admin/admin.php?page=wps_overview_page"
![image](https://user-images.githubusercontent.com/21234683/189349444-c9ddfca9-00f8-4390-81ee-f9b66c271ec3.png)
![image](https://user-images.githubusercontent.com/21234683/189350837-d5686efa-3086-4180-b490-4b87a0b9a5f3.png)

**Comment by mostafasoufi** [comment]
Hello,

Thank you for opening the issue, please tell me what's the status code and response of the request

- https://capture.dropbox.com/O9vB4jmyn4CtpHzT
- https://capture.dropbox.com/arAuQij8f0t2DuZY

**Comment by Doraemonsan** [comment]
The status code is 301, but there is no response
![image](https://user-images.githubusercontent.com/21234683/189354588-3d3251dc-a1a0-4958-a82e-9e9cd8456cf7.png)
![image](https://user-images.githubusercontent.com/21234683/189354638-6147c0ce-c77a-41b8-a9d1-d829fae6759b.png)

**Comment by mostafasoufi** [comment]
Most likely there is a PHP issue in the background,, can you please enable **WP_DEBUG** or **WP_DEBUG_LOG**? then you can see the error message.

**Comment by Doraemonsan** [comment]
Thank you. I set WP_DEBUG and WP_DEBUG_LOG to true in wp-config.php, but I didn't see the new log generation in wp-content/debug.log and the console (I used the debug mode for the first time)

**Comment by Doraemonsan** [comment]
Ohh, when I clicked on the plug-in option of wp-statistics, there was a new problem. It seems that it was really caused by PHP. The PHP version I am using now is 8.0.22. Maybe I should try to reduce the PHP version. Thank you again!
![image](https://user-images.githubusercontent.com/21234683/189361477-2df16b68-668d-4afa-b7f8-a41b538f590b.png)

**Comment by mostafasoufi** [comment]
It would be helpful if you would provide the latest errors of WP Statistics on your error_log, then we can compatible the plugin for PHP 8.0.
