### ISSUE TITLE
class-wp-statistics-install.php  - no index for field "ip" at table useronline & visitor

### ISSUE THREAD

**Issue by sufehmi** [wp-statistics/wp-statistics#414]
Hi, a client of mine recently contacted me and reported that their website was down. After checking everything, I found out that the MySQL server is overloaded with the following queries:

```
SELECT `location` FROM wp_statistics_visitor WHERE ip = '88.88.88.88' 

SELECT * FROM wp_statistics_useronline WHERE ip = '99.99.99.99'     
```    

I checked, and turned out there's no index for those fields.

So I execute the following command in MySQL :

```
alter table wp_statistics_useronline add index (ip);
alter table wp_statistics_visitor add index (ip);

```

And in an instant the website was up again, and CPU utilization in both webserver & database server went down to almost zero.

FYI, thank you.

**Comment by mostafasoufi** [comment]
The index `ip` is added to those tables and will be released in the next update.

Thank you for reporting!
