### ISSUE TITLE
Populate title for archive pages

### ISSUE THREAD

**Issue by hatsumatsu** [wp-statistics/wp-statistics#418]
Currently visits on archive pages (e.g. custom post type archives) are tracked without a page title. Would it be possible to automatically use the post type labels defined in the `register_post_type()` options `labels`?

**Comment by mostafasoufi** [comment]
Hi,

I appreciate you opening the issue. May I ask what kind of widget in the overview you mean?

**Comment by hatsumatsu** [comment]
@mostafasoufi Thanks for getting back. 

On my setup the issue occurs f.e. in `Statistics > Overview > Top 10 Pages` or `Statistics > Pages`. In these lists hits to post type archive pages appear with the correct path but with an empty (`-`) title. It would be cool if the title would be the name of the custom post type.

(In Settings `Track All Pages` is activated to track post type archive pages.)

**Comment by mostafasoufi** [comment]
Good idea! I've just supported it in this commit https://github.com/wp-statistics/wp-statistics/commit/1a33604fe6f80e6e9c2acc223ea9c87aeaa5e51c and will be released on the next version.
![Screenshot 2023-01-31 at 4 53 15 PM](https://user-images.githubusercontent.com/701520/215772485-0f58aa66-c169-44ba-88f6-05205a9fe77e.png)

Thank you!

**Comment by hatsumatsu** [comment]
@mostafasoufi Cool, thank you for the instant fix!

Just a minor input: 
- You could use get_queried_object() to retrieve the post type directly without the path.
- Your fix doesn't use __(), would be cool if the Prefix "Post Archive:" could be localized  :-)

**Comment by mostafasoufi** [comment]
Oh, forgot to use `__()`, thank you!

In the case of the `get_queried_object()`, actually, the function retrieves the current query object and doesn't support any argument. so in this case, we can't use that.

Best.
