### ISSUE TITLE
Function wpdb::prepare was called incorrectly

### ISSUE THREAD

**Issue by dev4press** [wp-statistics/wp-statistics#419]
I have found the issue in the `includes/class-wp-statistics-purge.php` file, on line 129, where the wpdb::prepare is used, and the number of prepare arguments doesn't match. You have 2 placeholders in the string, but there are 3 arguments passed to the prepare function, and that doesn't match.

**Comment by mostafasoufi** [comment]
Thank you @dev4press for reporting the issue, I've just fixed it in the `development` branch and will be released on the next version.
