### ISSUE TITLE
Most recent plugin is maxing out the CPU on our server.  

### ISSUE THREAD

**Issue by RkirkCBD** [wp-statistics/wp-statistics#420]
We have lots of posts and I'm thinking this update may be causing the server to max out our CPU?  Is there and option throttle it?
Improvement: Populate post type title for archive pages

**Comment by mostafasoufi** [comment]
Hi,

Actually, most of the sections that loaded helper [Pages::get_page_info](https://github.com/wp-statistics/wp-statistics/blob/development/includes/class-wp-statistics-pages.php#L295) are for getting data (SELECT) in admin area (not recording)

The only section is loaded this helper for record is [here](https://github.com/wp-statistics/wp-statistics/blob/development/includes/class-wp-statistics-visitor.php#L360) but the good news is that the helper is called without the `slug` parameter which the object relation is in a condition of slug.
https://github.com/wp-statistics/wp-statistics/blob/development/includes/class-wp-statistics-pages.php#L367-L376

So, you can safety update without performance impact.
