### ISSUE TITLE
Bug after update

### ISSUE THREAD

**Issue by 123Theatre** [wp-statistics/wp-statistics#421]
This is the message i received after updating your extension : 

Cette extension n’a pas pu se charger correctement et a été mise en pause dans le cadre du mode de récupération.

Une erreur de type E_PARSE a été causée dans la ligne 8 du fichier /home/theatremqr/www/wp-content/plugins/wp-statistics/includes/admin/pages/class-wp-statistics-admin-page-pages.php. Message d’erreur : syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)_

**Comment by mostafasoufi** [comment]
Hi,

Thank you for reporting the issue, It's fixed in this commit https://github.com/wp-statistics/wp-statistics/commit/39155dfc625ec406b7821693ed68e59f391ee0fa and the new version will be released soon.
