### ISSUE TITLE
ALTER Table is Force run after every update!

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#422]
Hi Team,
Unfortunately, after each plugin update, the following query is executed:
` ALTER TABLE `statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT`
Considering that the volume of my database is extremely high, it causes the site to be overloaded and unavailable
![Screenshot 2023-03-10 144232](https://user-images.githubusercontent.com/61265957/224304074-479a1b8b-e9d4-4abd-b56f-47aa78e8f364.png)

BR

**Comment by mostafasoufi** [comment]
I would like to thank you for raising the issue.

I noticed that the code block located at https://github.com/wp-statistics/wp-statistics/blob/master/includes/class-wp-statistics-install.php#L405-L407 is triggered only when the table collection is not the same as the database collection. This implies that if this code block executes every time an update is made, then it's possible that the table collection is not being updated successfully.

As a solution, I recommend manually updating the table collection to ensure that the updates are executed without any issues.
