### ISSUE TITLE
Feature request: date range picker with option "Last month"

### ISSUE THREAD

**Issue by g4rf** [wp-statistics/wp-statistics#423]
I like the new date range picker in the new version. It would be great, if you could add an option **Last month**, not meaning the last 30 days but the last month. So, if it's *March* now, I'll need to check the statistics of *whole February* for comparison with other months.

Thanks a lot for this great plugin!
Jan

**Comment by mostafasoufi** [comment]
Hey!

Thank you for opening the issue and your feedback, this sounds great, I'll ask our development team to work on this feature.

Best!

**Comment by mostafasoufi** [comment]
We've added this in this commit https://github.com/wp-statistics/wp-statistics/commit/c62767cd23a99d4fefc432517556c784b1837c78 and will be released on the next version.

Cheers
