### ISSUE TITLE
Searching for Blank date returns in Top Visitors Today page returns some error when debug log is enabled. 

### ISSUE THREAD

**Issue by kipmyk** [wp-statistics/wp-statistics#424]
From this line: 

https://github.com/wp-statistics/wp-statistics/blob/4f8cefeac9f85ea0ef1056fa013cc030bdac8188/includes/admin/templates/pages/top-visitors.php#L4

I recommend you add a required attribute to prevent breaking the site and displaying the following error when one searches without inputting the date as shown in the following GIF recording: https://a.supportally.com/i/csDCTR

To fix this, I suggest adding the required attribute to the Search Date Input field as follows:

`<input class="wps-search-date__input" id="search-date-input" type="text" size="18" name="day" data-wps-date-picker="day" value="<?php echo esc_attr($day); ?>" autocomplete="off" placeholder="YYYY-MM-DD" required>`

**Comment by mostafasoufi** [comment]
Thank you for reporting and the PR, merged to `development`.

Cheers

**Comment by kipmyk** [comment]
Hey @mostafasoufi, great to hear. Happy to help.  Thanks for the amazing work your are doing.
