### ISSUE TITLE
Problems after update with WP-stats

### ISSUE THREAD

**Issue by Stippel404** [wp-statistics/wp-statistics#429]
Since the update of WP 6.2.2 and the update of Wp-stats there is something terrible wrong. I'm using the plugin of WordFence so I can see on WP stats how many visitors we have on our website, on WordFence (WF) I can see more details. But... now all those vistors have the same link: 

**/wp-json/wp-statistics/v2/online?wp_statistics_hit_rest=yes&track_all=1¤t_page_type=page¤t_page_id=8969&search_query&page_uri=L2plenVzLWNocmlzdHVzL3JvbmRvbS1oZW1lbHZhYXJ0LWVuLXRlcnVna29tc3QvcGFyb3VzaWEv](https://www.....our webiste..../wp-json/wp-statistics/v2/online?wp_statistics_hit_rest=yes&track_all=1%C2%A4t_page_type=page%C2%A4t_page_id=8969&search_query&page_uri=L2plenVzLWNocmlzdHVzL3JvbmRvbS1oZW1lbHZhYXJ0LWVuLXRlcnVna29tc3QvcGFyb3VzaWEv**
And the  most strange thing is that this link is still repeating the whole day and night long. At echt visitor, so annoying.

Now I've deactivate your plugin, there are no strange messages at all.
I restore a backup yesterday, so now I upgrade WordPress and I hope there will be no strange wp-stats messages.
**My question is: whats wrong with Wp-stats?**

**Comment by mostafasoufi** [comment]
The endpoint `online` is for updating the current user online which is present on the website and not sure what's the problem here. can you explain in more detail?

Thank you!

**Comment by Stippel404** [comment]
Your explanation tells me that this is a problem with the WordFence plugin. Because, if I use another plugin with statistics, I see the same messages at Word Fence. So thank you for now, I will contact Word Fence.

**Comment by mostafasoufi** [comment]
I also asked our QA person to do a test with Wordfence.

**Comment by Stippel404** [comment]
> I also asked our QA person to do a test with Wordfence.

And whta does this person say?

**Comment by Stippel404** [comment]
Good afternoon,
About two hours ago, I reactivated the WP-stats plugin when I saw that there was an update. I hoped everything would be fine, it was also quiet on WordFence for the first fifteen minutes. After 2 hours, I looked at WordFence again and to my horror I see that I get all sorts of notifications through WP stats, every second with the same link.

https://www...../wp-json/wp-statistics/v2/online?wp_statistics_hit_rest=yes&track_all=1&current_page_type=page&current_page_id=14476&search_query&page_uri=L2V2YW5nZWxpc2F0aWUvcm9lcGluZy1lbi1iZWRpZW5pbmcv

I have replaced the name of our website with …. due to the privacy, but you can now clearly see what it is all about. To clarify, I have added a few more print screens:

- wp-json: this shows the notifications on WordFence, pay attention to the time of the notifications, they come in continuously.
![wp-json](https://github.com/wp-statistics/wp-statistics/assets/134269300/ae5c499b-cab3-4603-b797-547262e5f904)

This is what I see when I click on the above link
- JSON
![JSON](https://github.com/wp-statistics/wp-statistics/assets/134269300/4ae3e842-63c1-4e0e-9d4a-8b0ce7a97e69)

- Raw data
![message onbewerkte gegevens](https://github.com/wp-statistics/wp-statistics/assets/134269300/061fd07d-98c8-400f-80b5-95a988bd1cdc)

- Headers
![headers](https://github.com/wp-statistics/wp-statistics/assets/134269300/04b610f8-5d61-49ce-8ca7-bf9f4f222408)

You will understand:

 I immediately removed the wp-stats plugin. Too bad, because this plugin gave us the right information for years.

I hope you can help me to solve the problem, possibly repair the plugin.
Regards and thanks in advance,

By the way, WordFence also looked into it and sent me to you.

**Comment by Stippel404** [comment]
I reopen this issue, you will understand this after reading the message I wrote

**Comment by Stippel404** [comment]
I close this item, because I'm not satisfied at all.

**Comment by ighorbani** [comment]
Dear user @Stippel404 
I am Iman from VeronaLabs Development team. I have tested this feature with the Wordfence plugin and saw that the Wordfence plugin does not block this request and it works correctly!

You could disable this request from the WP Statistics plugin.
