### ISSUE TITLE
View a range of several years

### ISSUE THREAD

**Issue by ecations** [wp-statistics/wp-statistics#430]
Hi!

Is it possible to view several years of statistics with WP Statistics?

I tried to set a "custom range" but it seems to be limited for one month: when I change the month of the "start" date, the "end" date is also moving, making the range always extend to just a single month.

So is it currently not possible to view longer periods of statistics or am I simply missing something here?

**Comment by amirfallahii** [comment]
Hi @ecations 

We apologize for the delay in responding.

To view statistics for several years, you can use the "**Custom Range**" option in the Filter section. First, choose your start date, and then select your desired end date. This will display the statistics for the specified date range.

Please let me know if you have any further questions or if you need any clarification on the steps.

Regards,
