### ISSUE TITLE
Deprecated-Warning with PHP8 for Useragent.php

### ISSUE THREAD

**Issue by g4rf** [wp-statistics/wp-statistics#431]
Switching my Wordpresses to PHP8 reveals in debug mode a deprecation warning for the plugin. Would be nice, if you can solve this.

>**Deprecated:** Creation of dynamic property WhichBrowser\Analyser\Header\Useragent::$data is deprecated in **[…]/wp-content/plugins/wp-statistics/includes/vendor/whichbrowser/parser/src/Analyser/Header/Useragent.php** on line **11**
>
>**Deprecated:** Creation of dynamic property WhichBrowser\Analyser\Header\Useragent::$options is deprecated in **[…]/wp-content/plugins/wp-statistics/includes/vendor/whichbrowser/parser/src/Analyser/Header/Useragent.php** on line **12**

Thanks in advance,
Jan

**Comment by rezathriii** [comment]
Could you please provide the current version of WP Statistics you are using? If you haven't already done so, I highly recommend updating the plugin to the latest version. Once you have completed the update, kindly verify if the issue you reported has been resolved.

**Comment by g4rf** [comment]
The plugin is auto updated, so the installed version is 14.1.2. The deprecated warning presists.

![grafik](https://github.com/wp-statistics/wp-statistics/assets/18557074/0e4cfff0-7036-4cb4-9166-ce431cbd90b0)

**Comment by ighorbani** [comment]
Hi Dear User (@g4rf )
Thanks a lot for reporting this issue. I will check and fix it in following days. 

Best
Iman Ghorbani | Developer at VeronaLabs

**Comment by mostafasoufi** [comment]
Note for better debugging: It's for PHP v8.2

**Comment by ighorbani** [comment]
**Dear @g4rf** 
Thank you for reporting this issue, we have fixed it. Please update WP STATISTICS to the latest version in the next release.

**_Best
Iman Ghorbani
Developer at VeronaLabs_**
