### ISSUE TITLE
Page statistics for custom post types missing before 1st May

### ISSUE THREAD

**Issue by g4rf** [wp-statistics/wp-statistics#434]
Hello,

a customer of mine showed me a strange behaviour for the statistics of a single page:

Since a few weeks ago the statistics for a custom post type was okay. Since at latest 8th June the statistics only show click counts since 1st May, also for posts that are much older (the example shown here is a post from 2016):

![grafik](https://github.com/wp-statistics/wp-statistics/assets/18557074/6352a102-e772-4a6e-8f26-617692709e08)

For normal posts and pages the statistics seems to be working as expected.

The plugin is up to date (automatic updates).

Thanks in advance,
Jan

**Comment by amirfallahii** [comment]
Hi @g4rf 

We apologize for the delay in responding.

We have reviewed the problem you described and have taken steps to address it.
The latest version of the plugin includes these fixes, and we encourage you to update your installation.

Please let us know if you continue to experience any issues, and we will be happy to investigate further.

We appreciate your feedback and your patience as we work to improve the plugin's functionality.
Regards,
