### ISSUE TITLE
Deprecated-Warning with PHP8.2 for Useragent.php

### ISSUE THREAD

**Issue by adenyscomcompany** [wp-statistics/wp-statistics#435]
Hello,

We have the same issue described in this following ticket :  https://github.com/wp-statistics/wp-statistics/issues/431 

In fact, we still have the deprecated message, in Useragent.php file.

![image](https://github.com/wp-statistics/wp-statistics/assets/27069889/fd939a32-5ded-4a63-9353-29d982f31722)

Our project run on php 8.2 and we have 14.1.3.1 version of wp-statistics.

Could you solve this please ?

Thanks you in advance

**Comment by mostafasoufi** [comment]
Hello,
Thank you for opening the issue, actually, the fixes are not released yet, we'll do the new version this week.
https://github.com/wp-statistics/wp-statistics/commit/f9bb4045218b7141faab7614a727bad5b5413a69

Thank you!
