### ISSUE TITLE
wordpress wp visitor statics Foreground secondary encoding injection vulnerability 

### ISSUE THREAD

**Issue by laoquanshi** [wp-statistics/wp-statistics#436]
In WP Visitor Statistics 6.9.3, due to simple filtering of user data, secondary encoding injection can be performed and directly spliced into sql statements, resulting in sql injection vulnerability. 
 
Impact Version 
Osamaesh WP Visitor Statistics<=6.9.3
 Project Address: https://wordpress.org/plugins/wp-stats-manager/
vulnerability recurrence 
http://localhost/?wmcAction=wmcTrack&visitorId=121212%27+and+sleep(10)+or+%27
<img width="432" alt="image" src="https://github.com/wp-statistics/wp-statistics/assets/110451039/a9092055-31d5-48e6-8a16-361869e71058">
vulnerability analysis 	
 The entry function of the plug-in is as follows 
 
<img width="432" alt="image" src="https://github.com/wp-statistics/wp-statistics/assets/110451039/9ffe79f3-0f3a-42e8-bbc6-97eb22b6a402">
 In the initWsm initialization function, the following actions are registered.  The meaning is that the wsm_plugin_init function is called when the web site is visited 
 
<img width="360" alt="image" src="https://github.com/wp-statistics/wp-statistics/assets/110451039/ae0c973f-7038-4155-b4ab-dddb7b173598">
 The wsm_plugin_init is as follows.  When visiting a URL like http://xxxx/?  Enter wsmRequests if wmcAction=wmcTrack 
 
<img width="432" alt="image" src="https://github.com/wp-statistics/wp-statistics/assets/110451039/491f411f-c534-456a-b544-ce28ea8d2596">
 In the constructor of wsmRequests, due to the simple filtering of user data, you can perform secondary encoding injection to adjust fnHandleVisit 
 
<img width="432" alt="image" src="https://github.com/wp-statistics/wp-statistics/assets/110451039/103d6577-ce92-41e5-b489-f62cd0598c21">
 The parameters accessed for the first time are processed in fnHandleNewVisit
 
<img width="432" alt="image" src="https://github.com/wp-statistics/wp-statistics/assets/110451039/99c427e2-7f20-4721-b6a2-e864e68fb082">
 In fnInsertNewVisit, the passed-in visitorId is spliced and the sql statement is executed 
 
<img width="432" alt="image" src="https://github.com/wp-statistics/wp-statistics/assets/110451039/514dbc05-3329-4c00-8297-b4d33c7ac717">
repair mode 
 The vendor has not released a solution yet 
 Safety researcher Mr. Li personally suggested: 
 Use parameterized queries or prepared statements: Rather than just using escape processing, a better approach is to use parameterized queries or prepared statements to build SQL queries.  Parameterized queries are executed by separating the query statement from the parameters, thus separating the input data from the query logic and effectively preventing SQL injection attacks.

**Comment by mostafasoufi** [comment]
Hello,

Thank you for reaching out to us. It appears that there might be a slight confusion regarding the repository. This specific repository is meant for WP Statistics, not WP Visitor Statistics. To address the issue properly, we kindly request you to report it directly to the appropriate support team at [support@plugins-market.com](mailto:support@plugins-market.com).

Cheers
