### ISSUE TITLE
the page ranking don't support Chinese

### ISSUE THREAD

**Issue by RomaCredit** [wp-statistics/wp-statistics#437]
![image](https://github.com/wp-statistics/wp-statistics/assets/37257051/98c6ef55-ea54-4444-8f67-dda429cbf8cf)

You could see the picture attached. For example, I click the item 6, it comes out the link: https://www.zhibokanche.com/eq769%, which is not correct.

the correct link should be: https://www.zhibokanche.com/%e5%a5%87%e7%91%9e%e6%96%b0%e8%83%bd%e6%ba%90%ef%bc%9a%e5%a5%87%e7%91%9eeq7%e9%a2%84%e5%94%ae%e5%90%af%e5%8a%a8%ef%bc%8c%e4%bb%8a%e6%99%9a6%e7%82%b9%e8%87%b39%e7%82%b9%e5%ae%98%e6%96%b9%e6%97%97/

**Comment by mostafasoufi** [comment]
Thank you for reporting the issue, we've fixed it here https://github.com/wp-statistics/wp-statistics/commit/7dadc23ce61046c5e04e3097ce91b95f8c0fe8ed

Since the url is sanitized before, don't need to sanitize it again.
