### ISSUE TITLE
No graphs showing

### ISSUE THREAD

**Issue by horetol** [wp-statistics/wp-statistics#438]
Hello,
Since a few days (weeks ?) we have just raw numbers, no graphs. It seems that this happened since the last update of wp-statistics.
We have de-installed the plugin and then re-install it, but we still have no graphs, except for the most popular articles.
Thanks for your help.

**Comment by mostafasoufi** [comment]
Hey,

Can you please check out this [document](https://wp-statistics.com/resources/troubleshoot-with-cache-plugins/)? I assume there are some exclusions that caused the issue.
