### ISSUE TITLE
Role exclusion not working

### ISSUE THREAD

**Issue by WGroleau** [wp-statistics/wp-statistics#441]
I have always had **all** five roles checked for exclusion, yet it has always added my logged in visits and those of my contributors to the stats (several years on multiple blogs in three domains).  Is that because we have to make a visit before we can actually log in?  

If we go to the site and get recorded immediately before we can log in, then the exclusion is almost meaningless.

**Comment by amirfallahii** [comment]
Hi @WGroleau 

We have reviewed the problem you described and have taken steps to address it.

The latest version of the plugin includes these fixes, and we encourage you to update your installation. 

Please let us know if you continue to experience any issues with the exclusion settings, and we will be happy to investigate further.

We appreciate your feedback and your patience as we work to improve the plugin's functionality.
Best regards,
