### ISSUE TITLE
ALTER TABLE is still run on every update

### ISSUE THREAD

**Issue by VerosK** [wp-statistics/wp-statistics#442]
I am not sure but I suppose, that these bug #422  is still not fixed on our customers installation.

What we see:
After last three successfull updates (last update was to version 14.2) , we observe SQL statements to be called

    ALTER TABLE `wp_statistics_visitor` CHANGE `ID` `ID` BIGINT(20) NOT NULL AUTO_INCREMENT

    ALTER TABLE `" . DB::table('visit') . "` CHANGE `ID` `ID` BIGINT(20) NOT NULL AUTO_INCREMENT

and

    ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT

I suspect these call to be in `class-wp-statistics-install.php`  around line 403

https://github.com/wp-statistics/wp-statistics/blob/d24ae7be71746db3113de083372210379a29bd61/includes/class-wp-statistics-install.php#L403
       
 I suspect issues with table format detection in MySQL.
Our customer uses MySQL8 reporting itself as `Server version: 8.0.28-20 Percona Server (GPL)`

Can I help you with more debugging issues?

**Comment by VerosK** [comment]
Table wp_statistics_visitor:
```
mysql> show table status WHERE name LIKE 'wp_statistics_visitor'\G
*************************** 1. row ***************************
           Name: wp_statistics_visitor
         Engine: InnoDB
        Version: 10
     Row_format: Compact
           Rows: 661399
 Avg_row_length: 165
    Data_length: 109723648
Max_data_length: 0
   Index_length: 238239744
      Data_free: 7340032
 Auto_increment: 715360
    Create_time: 2023-10-09 22:14:35
    Update_time: 2023-10-09 21:57:21
     Check_time: NULL
      Collation: utf8mb4_general_ci
       Checksum: NULL
 Create_options: row_format=COMPACT
        Comment: 
```

**Comment by VerosK** [comment]
I also suspect issues with `wp_statistics_visitor`, as MySQL 8 uses `BIGINT` instead of `BIGINT(20)`, which is expected by the plugin.


```
mysql> describe wp_statistics_visitor;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| ID           | bigint       | NO   | PRI | NULL    | auto_increment |
| last_counter | date         | NO   | MUL | NULL    |                |
| referred     | text         | NO   |     | NULL    |                |
| agent        | varchar(180) | NO   | MUL | NULL    |                |
| platform     | varchar(180) | YES  | MUL | NULL    |                |
| version      | varchar(180) | YES  | MUL | NULL    |                |
| UAString     | varchar(190) | YES  |     | NULL    |                |
| ip           | varchar(60)  | NO   | MUL | NULL    |                |
| location     | varchar(10)  | YES  | MUL | NULL    |                |
| user_id      | bigint       | NO   |     | NULL    |                |
| hits         | int          | YES  |     | NULL    |                |
| honeypot     | int          | YES  |     | NULL    |                |
| device       | varchar(180) | YES  | MUL | NULL    |                |
| model        | varchar(180) | YES  | MUL | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+
14 rows in set (0.00 sec)
```

**Comment by mostafasoufi** [comment]
Hey @VerosK 

Thank you for reporting and explaining the issue. I'll ask our development team to review and test the table upgrade process again to try to reproduce the issue. I'll get back to you once we've fixed it.

**Comment by mostafasoufi** [comment]
@fscherwi I know. 🙂

Already on it.

**Comment by cristianuibar** [comment]
Thank you. I'll follow here for updates. Looking forward for this fix.

**Comment by mostafasoufi** [comment]
We've recently had some tweak fixes on the issue in 371c0002aecd15a47f706a4f90d47031e7abbc3c would be good to test this yourself to make sure everything works fine. @cristianuibar @VerosK

**Comment by DenisFlorin** [comment]
Hello @mostafasoufi!

We will test the fix at the end of the day and come back tomorrow with updates!

Thanks,

**Comment by DenisFlorin** [comment]
Hello! 

Actually, when I started testing, I realized that this wasn't possible because the issue occurs when we update the plugin.

Are you planning to release a new version soon?

Best regards,

**Comment by VerosK** [comment]
Hi @mostafasoufi, thank you for the fix.

Unfortunately I'm not fluent in  WordPress and I'm not able to do testing without some asistance.

Is there a document or some how-to guid how to test unreleased commits?

**Comment by DenisFlorin** [comment]
Hello,  @mostafasoufi!

I took the plugin from the development branch(which seems to have the fix you mentioned) and after pushing the changes, the queries like below started to appear:

```php
Query   |  123 | altering table                  | ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT
Query   |  115 | Waiting for table metadata lock | ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT; 
Query   |  112 | Waiting for table metadata lock | ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT;
Query   |  112 | Waiting for table metadata lock | ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT;
Query   |  102 | Waiting for table metadata lock | ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT;
Query   |   82 | Waiting for table metadata lock | ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT;
```

**Comment by mostafasoufi** [comment]
Thank you guys for testing, will check again and will get back to you soon!

**Comment by alifallahrn** [comment]
Hi @DenisFlorin,

We haven't experienced this issue in the development environment. 
Therefore, to identify and fix the problem, we need to debug it. 
To do this, I'd like you to add the code as shown in the image to the file `includes/class-wp-statisctics-install.php`, specifically on line `405`. After testing it again, please send us the log file from the path `wp-content/log.txt`.

```
// Start Log
file_put_contents(wp_normalize_path(WP_CONTENT_DIR) . '/log.txt', print_r([
    '$tbl_info' => $tbl_info,
    '$wpdb->collate' => $wpdb->collate
], 1), FILE_APPEND);
// End Log
```

![image](https://github.com/wp-statistics/wp-statistics/assets/25011798/062aa041-4409-4648-b9bd-73c02a19d196)

**Comment by DenisFlorin** [comment]
Hello,

Here is the file:
[log.txt](https://github.com/wp-statistics/wp-statistics/files/13162696/log.txt)

**Comment by alifallahrn** [comment]
Thank you @DenisFlorin!

We've fixed that issue.
The query will only run once after updating the plugin and won't run in subsequent updates.
It's ready for re-testing in the development branch.

**Comment by DenisFlorin** [comment]
Hello @alifallahrn,

I downloaded the plugin from the development branch, changed the version in readme.txt and wp-statistics.php and pushed these changes and after that I saw only one query running 

```php
Query   |   115 | altering table      | ALTER TABLE `wp_statistics_visitor` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT = COMPACT;
``` 

I think the last change fixed the issue. 

I will wait for the next release to check again.

Best regards,

**Comment by mostafasoufi** [comment]
Good to hear, thank you @DenisFlorin for testing and helping us.
