### ISSUE TITLE
Question about date picker error

### ISSUE THREAD

**Issue by kycasdzxc** [wp-statistics/wp-statistics#444]
#### When specifying a date in the statistics function, the date format is different. I live in Korea.

![image](https://github.com/wp-statistics/wp-statistics/assets/105793579/fcc5a6c5-f4bb-4371-8818-9e27ca88d77f)

####  This problem also causes problems when loading actual statistical data. As shown in the picture below, the value of 'rangeend' that goes to hidden appears as 'Invalid date'. Due to this problem, only the current statistical data is displayed, and if you edit the 'rangeend' of hidden in developer tools, it will work normally.

![image](https://github.com/wp-statistics/wp-statistics/assets/105793579/7121c5de-f9e4-4dc9-8828-97d7056a8f95)

#### can I know the commit history of the code?

**Comment by mostafasoufi** [comment]
Hello,

Thank you for addressing this issue. I understand that tracing the commit history can be challenging due to numerous subsequent updates. Therefore, I recommend upgrading to the latest version to take advantage of the numerous improvements, bug fixes, and new features.

Best
