### ISSUE TITLE
Homepage Hits not captured in "Top Pages"

### ISSUE THREAD

**Issue by Dead-Man-Walker** [wp-statistics/wp-statistics#447]
A page set as "homepage" is not captured in the section "Top Pages". 

This issue has been raised in this [plugin's wordpress forum ](https://wordpress.org/support/topic/hits-for-homepage-not-displayed-in-admin-page-list/) over a year ago.

**Comment by mostafasoufi** [comment]
We recently made some improvements in the development version that most-likely fixes this issue https://capture.dropbox.com/4AktunzboYx4F5ok

Can. you please test the [development](https://github.com/wp-statistics/wp-statistics/tree/development) version and let me know how it goes?

**Comment by Dead-Man-Walker** [comment]
Unfortunately, it does not fix the problem. Your screenshot refers to "Most Visited Pages" while my bug refers to "Top Pages" with post type "page":
![grafik](https://github.com/wp-statistics/wp-statistics/assets/11764115/d3bfc8da-0820-426a-ae99-0a4b55ca5ed1)

**Comment by mostafasoufi** [comment]
Fixed in https://github.com/wp-statistics/wp-statistics/commit/30d33ba72dbdb0932ed08ad9f0980624082795ad
