### ISSUE TITLE
Problems Detected on WP Hive Insights

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#451]
Hi Team,

You are probably familiar with [WP Hive Insights](https://wphive.com/) sites. This site runs WordPress plugins in a simulated environment and VPS and automatically checks Performance, problems, errors, compatibility, and other issues.
Unfortunately, problems have been identified by this site on all versions of your plugin that have not been resolved yet

Full stream in this link:
https://wphive.com/plugins/wp-statistics/

Do you have a plan to solve these problems?

BR

**Comment by mostafasoufi** [comment]
Hi @Sinapars,

Thanks for pointing out the issue. We indeed need to test the plugin with all the new PHP 8 versions, from 8.0 to 8.3. We have some old composer libraries in the plugin that may not work with the newer PHP versions, and this is probably why WP Hive is showing issues.

I'll set up a task for our team to do a full check and make sure everything is okay.

Best

**Comment by amirfallahii** [comment]
Hi @Sinapars 

Thank you for bringing this issue to our attention.

We have reviewed the report from WP Hive Insights and have taken steps to address the problems identified on our plugin. Please feel free to test the latest version of our plugin and let us know if you encounter any further issues.

We appreciate your feedback and will continue to work on improving the plugin.

Best regards,
