### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted

### ISSUE THREAD

**Issue by megseoh** [wp-statistics/wp-statistics#452]
I'm seeing a ton of these PHP Fatal errors in my error.log:

`2024/02/20 17:35:34 [error] 34724#34724: *33786 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /www/nerporg_483/public/wp-includes/class-wp-object-cache.php on line 146PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0" while reading response header from upstream, client: 2600:1005:b08b:6bb9:51c4:44de:26f8:b4ff, server: www.nerp.org, request: "GET /wp-json/wp-statistics/v2/hit?wp_statistics_hit_rest=yes&track_all=1&current_page_type=page&current_page_id=21900&search_query&page_uri=L2lzbHMtcHJvY2VlZGluZ3Mv&referred=&_=1708450528353 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-nerporg.sock:"`

Our PHP memory limit is 256M & our PHP memory limit (only for admin screens) is 512M.

**Comment by mostafasoufi** [comment]
Hello,

Can you please tell me what is your WP Statistics and WordPress version?

**Comment by mostafasoufi** [comment]
Hello,

We've made several performance optimizations in the latest release that should resolve the issue you reported. Please update your software to the latest version and check if the problem persists.

Best
