### ISSUE TITLE
Not Counting Correctly

### ISSUE THREAD

**Issue by veehikle** [wp-statistics/wp-statistics#464]
I just had a good day with over 2000 people reading an article on my website mrlocalhistory.org

Your plugin states I had only 30 users. Something happend and it's grossly understating statistics. I love this plugin but it's not calculating correctly.

Is there something wrong? I reinstalled Jetpack just to check and it verified the difference.

Please help

**Comment by mostafasoufi** [comment]
Hi @veehikle,

Sorry to hear about the stats issue. Could you check if "**Cache Compatibility**" is turned on under **Settings > Basic Tracking**? It might help. Let me know what you find, and we can determine the next steps.

I'm committed to helping you resolve this problem, so any additional information you can provide would be greatly helpful. Let's work together to get your statistics tracking correctly again.

Best

**Comment by mostafasoufi** [comment]
Hi,

We've recently published an article that addresses several key factors impacting data accuracy in WP Statistics. This guide provides insights and enhancements for more accurate data collection. You can read the full article here: [Enhancing Data Accuracy](https://wp-statistics.com/resources/enhancing-data-accuracy/).

Best
