### ISSUE TITLE
issue with the latest release

### ISSUE THREAD

**Issue by Clearified** [wp-statistics/wp-statistics#475]
Hello, 
A friend of mine has a website and When The last release was installed we noticed that plugin doesn't load @ the dashboard : https://imgur.com/vaMDe1s

even when I want to edit a post it shows https://imgur.com/UAmVeAn

Note that when we deactive the plugin the website goes good, and when restore a snapshot to use the previous version it seems everything goes well too.

**Comment by mostafasoufi** [comment]
Hi @Clearified,

Thank you for bringing this issue to our attention. If you're using an AdBlocker, could you please try disabling it to see if that resolves the issue?

Additionally, I've made a fix that might be related to the problem you're experiencing. You can view the details here: https://github.com/wp-statistics/wp-statistics/commit/d405c1c8d6f9441543f967c1f5a6a936b61075ac

Please let me know if this helps or if the issue persists.

Best regards

**Comment by mostafasoufi** [comment]
Sounds amazing!
