### ISSUE TITLE
Fatal Error after uodate of GeoIP database

### ISSUE THREAD

**Issue by Rustimation** [wp-statistics/wp-statistics#506]
Wordpress went int emergency mode and sent me an e-mail:
Ein Fehler vom Typ E_COMPILE_ERROR wurde in der Zeile 99 der Datei /var/www/html/wordpress/wp-content/plugins/wp-statistics/includes/vendor/geoip2/geoip2/src/Model/City.php verursacht. Fehlermeldung: Declaration of GeoIp2\Model\City::__isset($attr) must be compatible with GeoIp2\Model\AbstractModel::__isset(string $attr): bool

**Comment by mostafasoufi** [comment]
It appears that another plugin has loaded the MaxMind GeoIP.

Could you please provide a list of all the plugins currently installed on your site? You can do this by going to **Tools → Site Health → Info**, and then clicking on **Copy site info to clipboard**

**Comment by mostafasoufi** [comment]
Hey,

We are excited to announce that the issue has been fixed and will be included in version 14.9! You can check it out here: [GitHub Release 14.9](https://github.com/wp-statistics/wp-statistics/tree/release-14.9). This update, coming soon, will bring lots of amazing new features and improvements.

Cheers!
