### ISSUE TITLE
Improvement Request: Display notices only for admin user role!

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#507]
Hi Team,
Unfortunately, the following message is displayed for all users roles!

![image](https://github.com/wp-statistics/wp-statistics/assets/61265957/a59bcf1e-6723-4388-8414-0bc6254c7120)

I think it is better if this message is displayed only for the admin role

BR

**Comment by amirfallahii** [comment]
Hi @Sinapars 

Thank you for your feedback.
We will certainly consider this issue in future updates.

If you don't want this notice to be displayed, you can close it. By doing so, the notice will also be removed for other roles.

Regards,

**Comment by mostafasoufi** [comment]
Great idea! I've implemented a change to display this notice exclusively for administrators.

**Comment by Sinapars** [comment]
Big thanks, y'all!
