### ISSUE TITLE
Version 14.9.3 fails with XHR calls to /wp-admin/admin-ajax.php

### ISSUE THREAD

**Issue by ISO8807** [wp-statistics/wp-statistics#520]
For security reasons I have `.htaccess` set to block `/wp-admin` and use another prefix. This stops version 14.9.3 from working because it attempts XHR requests to `/wp-admin/admin-ajax.php`.

In the code I see references to `wps_js.global.admin_url `(which presumably defaults to `wp-admin`). I cannot find any way of setting this so how can itbe changed?

**Comment by mostafasoufi** [comment]
Hey,

The `wps_js.global.admin_url` is obtained from the `admin_url()` function, which you can see in the code [here](https://github.com/wp-statistics/wp-statistics/blob/master/includes/admin/class-wp-statistics-admin-assets.php#L432). If you change the wp-admin prefix, the `admin_url()` function will return the new URL.

Additionally, [I have added](https://github.com/wp-statistics/wp-statistics/commit/cfaaefc1113a1ae2aab2d93e4e1787bf59d09fd6?diff=split&w=1) a filter to modify these URLs, which you can use as shown below:

```php
add_filter('wp_statistics_admin_assets', function ($assets) {
    // Change to new admin URL, not wp-admin
    $assets['admin_url'] = 'http://localhost:10009/admin';
    $assets['ajax_url'] = 'http://localhost:10009/admin/ajax.php';
    $assets['meta_box_api'] = admin_url('ajax.php?action=wp_statistics_admin_meta_box');

    return $assets;
});
```

Best

**Comment by ISO8807** [comment]
Many thanks for the prompt and helpful response.

I already had a filter for the Ajax URL (based on a suggestion I found online):

```
function change_ajax_url($url, $path, $blog_id) {
  if ($path == 'admin-ajax.php')
    $url = site_url('/MYPREFIX/');
  return($url);
}

add_filter('admin_url', 'change_ajax_url', 10, 3);
```
This worked with version 14.9.2 by the way.

I added a small variation on what you suggested:

```
function change_wpstats_admin($assets) {
  $assets['admin_url'] = 'http://localhost/MYPREFIX';
  $assets['ajax_url'] = 'http://localhost/MYPREFIX/admin-ajax.php';
  $assets['meta_box_api'] =
    admin_url('admin-ajax.php?action=wp_statistics_admin_meta_box');
  return($assets);
}

add_filter('wp_statistics_admin_assets', 'change_wpstats_admin');
```

However, XHR posts are still being made to `http://MYIP/wp-admin/admin-ajax.php` and are failing "WP Statistics: Hit request failed with status 404".

It's as if your filter isn't taking effect. I don't know if my original filter is interfering with yours.

**Comment by ISO8807** [comment]
Ah. It looks like the `wp_statistics_admin_assets` hook is something that will appear in a future release. I was confused by the reference to `@since 14.0.4` in the code as I though it would already be there.

**Comment by mostafasoufi** [comment]
Sorry, I forgot to mention that. Yes, the `wp_statistics_admin_assets` hook is intended for the next version, which is v14.0.4. That's why it's referenced in the code as since 14.0.4. It will be available once that version is released.

Best

**Comment by ISO8807** [comment]
I experimentally added your planned change to version 14.9.3 as installed. However, the code continues to call `wp-admin/admin-ajax.php`. This appears to be hard-coded into `assets/js/tracker.js` and `assets/js/tracker.min.js` (which may be where this is coming from). I have enabled "Bypass Ad Blockers", so that might affect whether the filter does what I need.

I don't know exactly what was changed in 14.9.3, but this did all work OK in 14.9.2.

**Comment by mostafasoufi** [comment]
You're absolutely right! I forgot to mention this. It's fixed in the [development](https://github.com/wp-statistics/wp-statistics/commit/e0912416b8886d7cf97487e26bf31dfa3839b7bd?diff=unified&w=1#diff-16486ad2a497b2dd6dd7de21dafa273212d9687b74a05c6b157cae04a5ba700e) version and will be released in the next version, and the data will be retrieved dynamically from the backend.

**Comment by ISO8807** [comment]
Version 14.9.4 seems to be working fine. In fact I don't seem to need the `wp_statistics_admin_assets` hook. Many thanks for your rapid and effective resolution of this.

**Comment by mostafasoufi** [comment]
I am pleased to hear that your problem has been resolved.
