### ISSUE TITLE
WP-statistics interferring with editor

### ISSUE THREAD

**Issue by LeaMDavis** [wp-statistics/wp-statistics#540]
When the stats module is active, the following error occurs when I try to edit a page...
![image](https://github.com/user-attachments/assets/15325471-5660-4a91-af2e-a47dddc635cd)

This is the output of the "copy error" option (not sure how helpful it will be...
Oc@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:169:18
ah/<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:80:357
T@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:95:457
zj@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:227:428
Th@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:225
tj@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:152
Te@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:151
Pg/<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:68
unstable_runWithPriority@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260
Da@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:280
Pg@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:16
ha@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:451
Ja@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224:400
ch@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:93:81
e@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:20891
t@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:20958
pfJ3/B/instantiate/v</<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:15082
b@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:8589
+ekt/i/</</<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:1602
pfJ3/A/</<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:10455
pfJ3/L/</</<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:10762
dispatch@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:9449
+ekt/a/<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:1353
vsQm/e.default/t/c/r/<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9258
r@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9233
vsQm/e.default/t/c/u/<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9187
k4FQ/e.any@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:6329
vsQm/e.default/t/c/r/<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9258
r@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9233
vsQm/e.default/t/c/u/<@https://historicalsociety.unitingchurch.org.au/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9181

**Comment by mostafasoufi** [comment]
This issue is fixed in v14.10.2
