### ISSUE TITLE
The "wp-statistics-post-summary" plugin has encountered an error and cannot be rendered.

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#545]
Hi Team,
in The last Version plugin 14.10.1 I see this error in Gutenberg editor pages and posts
There is this error in the console too, but I am not sure if it is related to your plugin or not
BR
![image](https://github.com/user-attachments/assets/648b10a3-1fb5-4409-b52d-2aabb30b0eec)
![image](https://github.com/user-attachments/assets/94b0132f-0672-48c0-a228-f741bd319e45)

**Comment by amirfallahii** [comment]
Hi @Sinapars

Thank you for bringing this to our attention.  

We have identified an incompatibility between WP Statistics v14.10.1 and WordPress v6.5.5. Our development team is actively working on a resolution, which we plan to include in an upcoming release.  

In the meantime, we recommend ensuring that WordPress and all plugins remain up to date, as updating WordPress will resolve this issue.  

Additionally, if you prefer not to update WordPress right away, you can temporarily resolve the issue by disabling the "View Stats in Editor" option. To do this, navigate to Statistics > Settings > Display Options. This will prevent the error from displaying until we release a complete fix in the next minor update.  

We sincerely apologize for any inconvenience this may have caused and appreciate your continued support and understanding.  
Best regards,

**Comment by amirfallahii** [comment]
Hi @Sinapars 

We wanted to inform you that the issue you reported has been resolved in version 14.10.2, which was released just a few minutes ago. Please update the plugin to the latest version, and let us know if you encounter any further issues.

Thank you for your patience and understanding!
Best regards,
