### ISSUE TITLE
Critical Error PostsManager not found - Unable to access site

### ISSUE THREAD

**Issue by ForgottenHero** [wp-statistics/wp-statistics#558]
There has been a critical error on my website.

- WordPress version 6.6.2
- Active theme: Hello Elementor (version 3.1.1)
- Current plugin: WP Statistics (version 14.10.2)
- PHP version 8.2.23
- Elementor v3.24.4
- Elementor Pro v3.24.2

```
Error Details
=============
An error of type E_ERROR was caused in line 151 of the file /nas/content/live/mysitename/wp-content/plugins/wp-statistics/includes/class-wp-statistics.php.
Error message: Uncaught Error: Class "WP_Statistics\Service\Admin\Posts\PostsManager" not found in /nas/content/live/mysitename/wp-content/plugins/wp-statistics/includes/class-wp-statistics.php:151
Stack trace:
#0 /nas/content/live/mysitename/wp-content/plugins/wp-statistics/includes/class-wp-statistics.php(92): WP_Statistics->includes()
#1 /nas/content/live/mysitename/wp-includes/class-wp-hook.php(324): WP_Statistics->plugin_setup('')
#2 /nas/content/live/mysitename/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/mysitename/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /nas/content/live/mysitename/wp-settings.php(555): do_action('plugins_loaded')
#5 /nas/content/live/mysitename/wp-config.php(76): require_once('/nas/content/li...')
#6 /nas/content/live/mysitename/wp-load.php(50): require_once('/nas/content/li...')
#7 /nas/content/live/mysitename/wp-admin/admin-ajax.php(22): require_once('/nas/content/li...')
#8 {main}
  thrown
```

I wasn't able to initialise recovery mode, so I disabled WP Statistics via FTP for now.

I have another site also with WP Statistics which is working fine.
It's details are identical but with a different theme and not using Elementor:

- WordPress version 6.6.2
- Active theme: (Custom theme)
- Current plugin: WP Statistics (version 14.10.2)
- PHP version 8.2.23

**Comment by mhdizmni** [comment]
Hello @ForgottenHero,

Thank you for bringing this issue to our attention!

We have applied a fix in [this commit](https://github.com/wp-statistics/wp-statistics/commit/45683f8cb6ce4a5de764a77607966ab53e7f615f).  Please download the plugin from [the development branch](https://github.com/wp-statistics/wp-statistics/tree/development) and test it to see if the issue is resolved.

We look forward to your feedback.

Thank you for your cooperation!

Regards
