### ISSUE TITLE
not referesh data for some hours

### ISSUE THREAD

**Issue by LiangYongAI** [wp-statistics/wp-statistics#565]
I found this plugin always not referesh data for some hours, when it worked, the missing data will appear suddenly, It happened three times for me. Do you know the reason?

**Comment by mhdizmni** [comment]
Hi @LiangYongAI,

Thank you for reaching out to us!

Could you please provide details about the issue you are experiencing? Specifically, in which section of the plugin are you noticing the missing data?

Providing screenshots/screencasts can significantly help us investigate the issue and provide you with more accurate answers.

Thank you for your cooperation!

Regards

**Comment by LiangYongAI** [comment]
![image](https://github.com/user-attachments/assets/f3bf76b0-c9f7-48f7-aa3b-5b0dc3666f58)
![1728879697156](https://github.com/user-attachments/assets/c40dfed6-7197-4745-8564-736cf00d9c2c)

**Comment by mhdizmni** [comment]
Could you please check the timezone setting under Settings > General > Timezone in your WordPress admin area?

WP Statistics logs the date and time based on the configured timezone. For example, if you reside in New York but your site's timezone is set to London, a new log submitted on October 15 at 1:00 AM (New York time) will be displayed as 6:00 AM (London time).

Thank you for your cooperation!

Regards

**Comment by LiangYongAI** [comment]
I use UTC+8 timezon
![image](https://github.com/user-attachments/assets/7f50cb53-c1a3-4827-b980-3727f6ab2c29)
It is 3:24 at UTC+8， but I got some data miss form 11:54pm, before that it is normal。
![image](https://github.com/user-attachments/assets/ab8e2d56-14c0-46cf-ac50-0c5855612d3a)
I use another plugin, It is normal until now.
![image](https://github.com/user-attachments/assets/97df6775-c7b1-4ebc-a8de-1050d9c89f3f)
I want to use WP statisctic, It is really useful if this is work.

**Comment by LiangYongAI** [comment]
the data missing everday between 0:00 am to about 7:00 am at UTC+8 timezone.  the same everyday

**Comment by LiangYongAI** [comment]
@mhdizmni can you give me some answer? thanks?

**Comment by LiangYongAI** [comment]
I tested and found that version wp-statistics-14.9.4 is ok, and version wp-statistics-14.10.x has this problem. can you found the root cause?

**Comment by mhdizmni** [comment]
@LiangYongAI
Please accept our apologies for the delayed response, and thank you for the details.

Could you also let us know the name of the other plugin you are currently using, the one you are comparing WP Statistics data with?

Thank you for your cooperation!

Regards

**Comment by LiangYongAI** [comment]
another plugin I used is "Visitor Traffic Real Time Statistics".
the main point is wp-statistics work wrong after 0:00 at middle night with  version 14.10.x.
the data will not display from then, and will appear at about 8:00am suddenly. I set utc+8 timezone. 
You can test it yourself.

**Comment by mhdizmni** [comment]
After reviewing the recorded data in different timezones, I can assure you there is no issue with WP Statistics.

However, I noticed something in the screenshots you shared in [this comment](https://github.com/wp-statistics/wp-statistics/issues/565#issuecomment-2412053608); the filter you set is "Last 30 Days (Sep 15 - Oct **14**)". That's why the data for Oct **15** is not displayed.

Changing the date range from the top right corner should fix the problem.
![image](https://github.com/user-attachments/assets/6fcc37e8-e865-48c9-9950-d0c6d0ad3860)

Could you please check and confirm?

Thank you!

**Comment by LiangYongAI** [comment]
Yes, Maybe this is the root cause! I will check it tonight. but I think your design is not reasonable. your should update the date filter automatic after 0:00 am. according to the timezone I set, but not update the date filter according UTC+0.  I noticed that the filter is added at 14.10.x. can you please fix it?

**Comment by mhdizmni** [comment]
I will review this at midnight and notify our team for further investigation and a possible fix.

Thank you for your continued support!

Regards
