### ISSUE TITLE
API to Query Visitor Information by IP Address or Other Parameters?

### ISSUE THREAD

**Issue by LiangYongAI** [wp-statistics/wp-statistics#571]
I am currently using WP-Statistics to track visitor information on my WordPress site. I was wondering if your plugin provides any API or method that allows users to query visitor information (such as geolocation, referrer, and visit history) based on specific parameters, for example, an IP address.

My use case is that I would like to programmatically fetch details about a visitor using their IP address. Is there a way to do this directly via the API, or would I need to query the database directly?

If this is not currently available, is there any plan to support such a feature in the future?

Thank you for your time and looking forward to your response!

**Comment by mhdizmni** [comment]
Hi @LiangYongAI,

Thank you for reaching out to us!

You may use our `VisitorsModel` model to get the visitor data.

Please refer to the following piece of code as an example:

```
$visitorMode = new \WP_Statistics\Models\VisitorsModel();
$visitor = $visitorMode->getVisitorData(['ip' => 'THE IP ADDRESS HERE']);
```

If you need further assistance or have any questions, please don’t hesitate to reach out—we're always here to help!

Regards

**Comment by LiangYongAI** [comment]
I am currently using the method provided in a previous response to query visitor data by IP address in WP-Statistics:

function wp_statistics_query_visitor_data($ip) {
    if (class_exists('\WP_Statistics\Models\VisitorsModel')) {
        $visitorModel = new \WP_Statistics\Models\VisitorsModel();
        $visitor = $visitorModel->getVisitorData(['ip' => $ip]);

        if ($visitor) {
            echo '<h3>Visitor Data for IP: ' . esc_html($ip) . '</h3>';
            echo '<pre>';
            print_r($visitor);
            echo '</pre>';
        } else {
            echo '<p>No visitor data found for this IP address.</p>';
        }
    } else {
        echo '<p>WP Statistics plugin is not installed or the model is not available.</p>';
    }
}

However, when I input an IP address that is stored as plaintext in the database, the method seems to return the first record in the table, regardless of the IP entered.

Upon further inspection, I realized that this issue might be due to the way the IP address is handled by the getVisitorData() method. I suspect the method hashes the input IP before querying the database. In my case, the WP-Statistics settings is disabled hash IP addresses, and the IP addresses are now stored as plaintext.
![image](https://github.com/user-attachments/assets/078d0300-f4a4-4979-8166-2af7d1d7f80b)

when I query ip: 71.65.169.203,but the query result is :
![image](https://github.com/user-attachments/assets/578a9c01-73c9-4486-82bf-50328c8385a4)


Therefore, it seems the method is hashing the input IP, but the database contains plaintext IP addresses, resulting in no match and thus always returning the first record.

Question: Is there a way to adjust this method to account for plaintext IPs stored in the database? If not, would you suggest a workaround for querying visitor data when the database contains plaintext IP addresses instead of hashed ones?

Thank you for your help! @mhdizmni
