### ISSUE TITLE
Security Improvement Suggestion

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#586]
Hello Team,
I hope you are well

Recently, my websites have been under heavy attacks using various methods, including DDoS, XSS, and SQL Injection. Your plugin has been extremely helpful in providing valuable information, such as the time the attack started, the number of requests sent, the attacker’s IP, operating system, and more. Additionally, the Wordfence plugin has been very effective in blocking these attacks altogether.

However, I noticed an issue, and I’m unsure if this could be considered a security improvement or not, and whether it should be addressed by your plugin using methods like data sanitization before being sent to the database.

The issue is that the attacker was able to insert SQL Injection and XSS-related commands into your plugin’s tables, and these entries were even counted as page or post views in the plugin’s dashboard.

For example, let’s say there’s a page on the site with the following URL:

`https://github.com/wp-statistics/`

The attacker performed various tests on this URL, such as:

`https://github.com/wp-statistics/-1 OR 2+443-443-1=0+0+0+1 --`

or

`https://github.com/wp-statistics?-1' OR 2+518-518-1=0+0+0+1 or 'Hq3ehwqI'='`

**Screenshot from table:**

![image](https://github.com/user-attachments/assets/27610cd7-b600-4f08-810b-4fc203f8bbf3)

![image](https://github.com/user-attachments/assets/ae7c2637-cf42-405b-8925-cfd3549db72d)

![image](https://github.com/user-attachments/assets/b22e5209-f0aa-4000-938f-1d07ec5c3b5d)

**Dashboard:** 

![image](https://github.com/user-attachments/assets/bf686ea4-d3e5-41d5-a306-a58cb62733ed)

I’d appreciate your thoughts on this matter.
BR

**Comment by mhdizmni** [comment]
Hi @Sinapars,

Thank you for reaching out and for sharing your observations. We’re glad to hear that WP Statistics has been helpful in monitoring and analyzing traffic during these attacks.

Regarding the issue you mentioned, I’ve forwarded this to our development team for further review. They will carefully analyze the case to determine if additional measures can be implemented to address this behavior effectively while maintaining accurate reporting.

We truly appreciate you bringing this to our attention, as your feedback plays a crucial role in helping us improve. I will get back to you as soon as I have an update from the team.

Thank you!

Regards,
Matthew

**Comment by mhdizmni** [comment]
Hi again, dear @Sinapars,

Kindly note that WP Statistics actively blocks SQL injection attempts using a predefined list of patterns, which you can review [here](https://github.com/wp-statistics/wp-statistics/blob/master/includes/class-wp-statistics-helper.php#L1908:L1946).

Additionally, we have implemented a filter ([this commit](https://github.com/wp-statistics/wp-statistics/commit/b82adf74fb2edb91accb90f47478929659a2fd82)) in our [development version](https://github.com/wp-statistics/wp-statistics/tree/development) which will be included in an upcoming release. This feature allows users to add their own patterns for SQL injection prevention and blocking unwanted hit requests.

You can implement this in your site by adding the following hook to your `functions.php` file:
```
add_filter('wp_statistics_injection_patterns', function ($patterns) {
    $patterns[] = '/(-1\'?\s*OR)/i';
    return $patterns;
});
```

Please note, while these patterns significantly reduce SQL injection risks, attackers may employ new and varied techniques.

I would also like to remind you of our previous offer of a 100% discount on WP Statistics Premium. Please feel free to reach out via our [contact form](https://wp-statistics.com/contact-us/general-questions/) if you would like to take advantage of this offer.

Looking forward to hearing from you, and thank you once again for your continued support and for helping us improve.

Regards,
Matthew
