### ISSUE TITLE
Suggestion: Set Default Start Date Filter to Post/Page Publish Date

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#597]
Hello Team,

I would like to suggest an enhancement regarding the default start date for filters. Currently, when the filter is set to **“All Time,”** the default **start date is set to 1970-01-01**. While this might not be a significant issue when working with raw numerical data (since we only deal with aggregate numbers), it becomes problematic when the filter is applied to **charts**.

Since there is no data for those years, this setting causes the chart to appear **cluttered and compressed** around the years with actual data, making it challenging to analyze the chart effectively.

I believe it would be highly beneficial if the default start date could be set to the **publish date of the post or page (minus one day)** instead of **1970-01-01**. This change would result in cleaner, more meaningful charts, making data analysis much more practical.

Additionally, this adjustment could likely reduce query execution times, as the filtered range would be more relevant and efficient to process.

Thank you for considering this suggestion, and I hope it can be implemented to further improve this already excellent plugin.

Best regards,
Sina

![image](https://github.com/user-attachments/assets/72f536eb-438b-4bf5-857e-b6d549089d3a)
![image](https://github.com/user-attachments/assets/da8df95b-97be-4eec-b053-8704bea0f7e5)

**Comment by mhdizmni** [comment]
Hello @Sinapars,

Thanks for bringing this to our attention!

We’ll be addressing the issue in an upcoming release. Please note that the January 1970 start date is a UI issue and does not affect query performance.

We appreciate your suggestion and help in improving WP Statistics!

Regards,
Matthew

**Comment by Sinapars** [comment]
Hello @mhdizmni,

Thank you for your reply and for addressing this issue in an upcoming release. I’d like to clarify that the January 1970 start date is not just a UI issue. When using plugin like **Query Monitor** to analyze queries, it becomes clear that the database query also uses this date as the start point.

**In my previous suggestion**, I proposed setting the default start date to the post/page **publish date minus one day**. However, I’ve realized that this approach could have a potential problem: 
if the publish date of the post or page is **modified** by an admin or another user, the displayed data might become **inaccurate**.

With this in mind, I believe a more **logical and reliable solution** would be to set the **default start date** to the earliest date where actual **data exists in the database**. This approach seems more accurate and avoids the issues caused by relying on post/page publish dates.

Thank you again for your efforts in improving WP Statistics, and I hope this updated suggestion helps enhance the user experience even further.

Best regards,
Sina

**Comment by mhdizmni** [comment]
Dear @Sinapars,

You are correct about the queries. When the filter is set to "All Time", the following date range filter is applied to multiple queries, which can impact performance:
```
BETWEEN '1970-01-01'
AND 'XXXX-XX-XX'
```

![image](https://github.com/user-attachments/assets/76749840-f68d-43ac-9a54-408846815eb7)

We are actively working to enhance the plugin's performance in future releases.

Additionally, please note that the January 1970 start date shown **in the charts** is a UI-related issue and will be addressed in an upcoming update.

We truly appreciate your continued support and your regular sharing of feedback with us. We will certainly take them into consideration to improve WP Statistics.

Regards,
Matthew

**Comment by mhdizmni** [comment]
Dear @Sinapars,

We’ve resolved the issue regarding the starting point of the data, which will be included in **version 14.11.4**.

The starting date is now set to the publish date of the post, or the first post in the report, whether it’s a single post report or not.

The fix is reflected in both the charts and queries.

Thank you for your continued support!

Cheers,
Matthew
