### ISSUE TITLE
FYI: Introducing Plugin Check (PCP), Enhancing WordPress Plugin Standards

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#608]
Hi Team,

Recently, I noticed that some popular plugins I used were **temporarily removed from the WordPress repository** due to security reviews conducted by the WordPress team.
After a few days, when these plugins were return to the repository, their changelogs mentioned the following update:

**Fixed: Errors reported by Plugin Check (PCP)**

**Plugin Check (PCP) Link is:**
https://wordpress.org/plugins/plugin-check/

Before this, I had never heard of the **Plugin Check (PCP)** tool,  nor did I know about its purpose. I’m not sure if it’s a new tool developed by the WordPress team or if it’s been around for a while. Either way, it seems like an excellent tool for evaluating plugins developed by programmers, as it examines plugins from various aspects to ensure maximum compatibility with WordPress development standards.

I tested several popular plugins, including yours, using this tool. It provided numerous suggestions for improving your plugin—ranging from security concerns to performance optimizations and more.

Honestly, my primary reason for starting this discussion is to express concern about the potential removal of your plugin from the WordPress repository by the WordPress team. Additionally, I wanted to inform you about this tool (in case you’re not already familiar with it) so you might consider addressing the issues flagged by it. 

BR,
Sina

**Comment by mhdizmni** [comment]
Dear @Sinapars,

We will review the PCP and address any valid issues as part of our commitment to continually improving WP Statistics.

Thank you for your ongoing suggestions and support in helping us enhance the plugin.

Please keep them coming!

Regards,
Matthew

**Comment by mostafasoufi** [comment]
Hello Sina,

Thank you for mentioning the Plugin Check tool.

Yep, Plugin Check is kind of an older tool from WordPress.org that helps plugins meet the requirements during the initial submission process. Honestly, we don’t run it regularly, but occasionally, when security issues are reviewed, we use it. Since we've added new functionality recently, we’ll need to perform another review to ensure everything is in line.

Anyway, I’m considering adding this as a new workflow for every PR to help us review suggestions and see the check results directly with each PR:

- [plugin-check-action](https://github.com/WordPress/plugin-check-action)
- [plugin-check](https://github.com/WordPress/plugin-check)

Thanks again for the heads-up!

Best regards,

**Comment by Sinapars** [comment]
Hi @mostafasoufi Jan,

Thank you for your attention to this matter. I’m glad to hear that you’re familiar with the Plugin Check tool and already have plans to review the issues it reports.
Honestly, my main concern was to prevent a situation similar to what happened with other plugins **(temporary removal from the WordPress repository)** from happening to your plugin as well. That’s why I felt it was important to inform you about this.

Moreover, since I personally tested your plugin using this tool and noticed that it flagged errors, warnings, and other issues, my concern grew even more. I felt it was my responsibility to bring this to the attention of your excellent team.

i'm think Achieving 100% compatibility with this tool could be a major strength and differentiator for your plugin. It’s something you could highlight in the WordPress repository or on your own site with a badge in the future. For example, tools like **WP Hive** previously flagged errors in your plugin, but after notifying you, those issues were fixed.
https://wphive.com/plugins/wp-statistics/

Mostafa Jan, thank you once again for your constant attention and the great of your entire team!

BR
Sina

**Comment by mostafasoufi** [comment]
Hi Sina,

Thanks for pointing this out. Yep, we’re aware of the issues flagged by the Plugin Check tool and are working on fixing them to ensure full compatibility with the repository.

I’ve also recently added AI code reviews for PRs, which should help with code reviews. https://github.com/wp-statistics/wp-statistics/pull/612

Best
