### ISSUE TITLE
Site tracking issue

### ISSUE THREAD

**Issue by benisdev-py** [wp-statistics/wp-statistics#613]
Hey, 

i freshly isntalled the plugin working fine so fare but i have one Problem.
when a vistor comes to my main home page and than navigates to my contact page or any other site and than go back to my homepage I only see that he was first on contact page and than on home page but the first site is not shown. 
Is that correct? that one site is only shown with one timestamp?

**Comment by mhdizmni** [comment]
Hi @benisdev-py,

Currently, the "Recent Views" section shows the latest pages a user has visited, displaying only the most recent visit to each page. For example, if a user views Page A multiple times, only the latest visit will appear.

**We are planning an update to the "Recent Views" section that will display each visit to the same page separately, providing a more detailed view of user activity.**

Regards,
Matthew

**Comment by benisdev-py** [comment]
Hey, 

thank you for the very quick response. 
Okay can you tell me how long this take to imlement? because this is the only thing that keeps me to still have matomo active. But i think if you add this it would be the best and cleanest statistics plugin for wordpress at all ;)

**Comment by mhdizmni** [comment]
Dear @benisdev-py,

We aim to include this in **version 14.12**, but the exact release date is yet to be confirmed.

Also, we’re thrilled to know that you find our product useful. Thank you for your kind words!

Regards,
Matthew
