### ISSUE TITLE
Current namespace syntax not working in the PHP 5.4

### ISSUE THREAD

**Issue by mostafasoufi** [wp-statistics/wp-statistics#85]
There is a problem when the PHP version is 5.4. Because doesn't support this syntax for the namespace.

```
<?php
namespace {

}
```
WP support link:
https://wordpress.org/support/topic/unexpected-after-upgrade-to-12-2-1/

It's better to remove.

**Comment by Dedi-Data** [comment]
fixed
https://github.com/wp-statistics/wp-statistics/pull/86

**Comment by mostafasoufi** [comment]
I have been a commit (65d6b022a4280248646731a363408f5f63971c70) to update instance classes.
