### ISSUE TITLE
Log stats using Ajax

### ISSUE THREAD

**Issue by Lostars** [wp-statistics/wp-statistics#94]
When I use wp-super-cache and enable html cache, wp-statistics won't count again.
Can it support a ajax way to statistics？

**Comment by Dedi-Data** [comment]
Hi,
This is doing
Please wait for next version

**Comment by Dedi-Data** [comment]
https://github.com/wp-statistics/wp-statistics/pull/109
@mostafasoufi

**Comment by mostafasoufi** [comment]
This feature added in this commit (https://github.com/wp-statistics/wp-statistics/commit/634c76eab34c9beff8e5506bf648f1f68b17e834), could you please have a test in your WordPress?
We want to make sure this feature works well.

Thank you.

**Comment by Lostars** [comment]
Hello,I'm very sorry to give you a feedback so late.
It's not work on my website(https://minei.me) which is hosted by Tencent cloud CDN,
and show no visit data on main dashboard since the latest version update.

**Comment by Lostars** [comment]
![image](https://user-images.githubusercontent.com/13404175/48992569-5be3f800-f173-11e8-9593-e37c410fe735.png)
I want to know which wordpress build-in api has been used in this feature, because I'm using Disable REST API plugins to avoid unauthorized access. Thanks!

**Comment by mostafasoufi** [comment]
@Lostars 

Thank you for checking 👍
