### ISSUE TITLE
Add shortcodes Buttons

### ISSUE THREAD

**Issue by Dedi-Data** [wp-statistics/wp-statistics#99]
Add shortcodes Buttons
to add shortcodes in editor

https://wp-statistics.com/2017/05/26/shortcodes/

**Comment by mostafasoufi** [comment]
The shortcodes already available in the beta version and will be released in the next version.

![screenshot-localhost-2018 10 20-10-29-57](https://user-images.githubusercontent.com/701520/47252518-1edd6500-d453-11e8-8a1b-c7412062671b.png)
